;;; nskk-kana.el --- Kana character classification and conversion -*- lexical-binding: t; -*-

;; Copyright (C) 2026 NSKK Contributors

;; Author: takeokunn <bararararatty@gmail.com>
;; Maintainer: takeokunn <bararararatty@gmail.com>
;; URL: https://github.com/takeokunn/nskk.el
;; Version: 0.1.0
;; Keywords: i18n

;; This file is NOT part of GNU Emacs.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Kana character utilities for NSKK (Layer 1: Core Engine).
;;
;; Layer position: L1 (Core Engine) -- depends only on nskk-prolog.
;;
;; Provides kana character classification predicates and bidirectional
;; conversion functions used throughout the conversion pipeline:
;; - Hiragana <-> katakana conversion (code-point arithmetic)
;; - Zenkaku (full-width) <-> hankaku (half-width) katakana conversion
;; - Unicode character classification predicates
;;
;; All classification predicates and their Prolog rules are installed at
;; module load time.  `nskk--kana-define-range-predicate' simultaneously:
;;   1. Asserts a Prolog range rule for cross-predicate queries.
;;   2. Defines the corresponding ELisp predicate.
;; Han (kanji) and the Japanese composite predicate use direct Prolog
;; rule assertions, since they span disjoint ranges or are disjunctions.
;;
;; `nskk-kana-initialize' populates Prolog facts from the zenkaku/hankaku
;; hash tables (idempotent).  Hash table caches provide O(1) hot-path
;; performance for string conversion.
;;
;; Prolog predicates maintained by this module:
;; - `kana-hiragana/1'          -- range rule: U+3040-U+309F
;; - `kana-katakana/1'          -- range rule: U+30A0-U+30FF
;; - `kana-hankaku-katakana/1'  -- range rule: U+FF65-U+FF9F
;; - `kana-han/1'               -- two range rules: U+4E00-U+9FFF, U+3400-U+4DBF
;; - `kana-japanese/1'          -- disjunction of the four ranges above
;; - `zenkaku-to-hankaku/2'     -- hash-indexed facts (string -> string)
;; - `hankaku-to-zenkaku/2'     -- hash-indexed facts (string -> string)
;; - `kana-conversion/3'        -- (mode direction converter-fn) kana conversion dispatch table
;;
;; Key public API:
;;
;; defsubst predicates (inlined by byte-compiler, no /k variant):
;; - `nskk-kana-hiragana-p'                  -- test hiragana char (defsubst)
;; - `nskk-kana-katakana-p'                  -- test katakana char (defsubst)
;; - `nskk-kana-hankaku-katakana-p'          -- test half-width katakana (defsubst)
;;
;; defun/k functions (always succeed, return a value):
;; - `nskk-kana-hiragana-to-katakana'        -- convert single char
;; - `nskk-kana-katakana-to-hiragana'        -- convert single char
;; - `nskk-kana-zenkaku-to-hankaku'          -- convert zenkaku string/char (always succeeds)
;; - `nskk-kana-hankaku-to-zenkaku'          -- convert hankaku string/char (always succeeds)
;;
;; defun/k functions (2-continuation: may fail):
;; - `nskk-kana-han-p'                       -- test han (kanji) char
;;   (Prolog-backed: supports cross-predicate Prolog queries; not defsubst)
;; - `nskk-kana-japanese-p'                  -- test any Japanese char
;; - `nskk-kana-string-hiragana-to-katakana' -- convert string; fails if not a string
;; - `nskk-kana-string-katakana-to-hiragana' -- convert string; fails if not a string
;;
;; CPS (/k) variants for pipeline composition:
;; (all generated by defun/k or defun/done; always call on-found/on-done)
;; - `nskk-kana-han-p/k'
;; - `nskk-kana-japanese-p/k'
;; - `nskk-kana-hiragana-to-katakana/k'      -- defun/k: always succeeds
;; - `nskk-kana-katakana-to-hiragana/k'      -- defun/k: always succeeds
;; - `nskk-kana-string-hiragana-to-katakana/k'
;; - `nskk-kana-string-katakana-to-hiragana/k'
;; - `nskk-kana-zenkaku-to-hankaku/k'        -- defun/k: always succeeds
;; - `nskk-kana-hankaku-to-zenkaku/k'        -- defun/k: always succeeds
;; - `nskk-kana-initialize/k'  (defun/done: on-done continuation)
;;
;; Unicode ranges used:
;; - Hiragana: U+3040-U+309F
;; - Katakana: U+30A0-U+30FF
;; - CJK Unified Ideographs (Kanji): U+4E00-U+9FFF
;; - CJK Unified Ideographs Extension A: U+3400-U+4DBF
;; - Half-width Katakana: U+FF65-U+FF9F

;;; Code:

(require 'nskk-prolog)
(require 'nskk-cps-macros)

;;;; Customization

(defgroup nskk-kana nil
  "Kana character classification and conversion settings."
  :prefix "nskk-kana-"
  :group 'nskk)

;;;; Unicode Code Point Constants
;;
;; Based on Unicode Standard 15.0.

(defconst nskk--kana-hiragana-start #x3040
  "Start code point of hiragana block (Unicode U+3040).")

(defconst nskk--kana-hiragana-end #x309F
  "End code point of hiragana block (Unicode U+309F).")

(defconst nskk--kana-katakana-start #x30A0
  "Start code point of katakana block (Unicode U+30A0).")

(defconst nskk--kana-katakana-end #x30FF
  "End code point of katakana block (Unicode U+30FF).")

(defconst nskk--kana-han-start #x4E00
  "Start code point of CJK Unified Ideographs block (Unicode U+4E00).")

(defconst nskk--kana-han-end #x9FFF
  "End code point of CJK Unified Ideographs block (Unicode U+9FFF).")

(defconst nskk--kana-han-extension-a-start #x3400
  "Start code point of CJK Unified Ideographs Extension A (Unicode U+3400).
Contains rare and historical kanji characters.")

(defconst nskk--kana-han-extension-a-end #x4DBF
  "End code point of CJK Unified Ideographs Extension A (Unicode U+4DBF).")

(defconst nskk--kana-hankaku-katakana-start #xFF65
  "Start code point of half-width katakana block (Unicode U+FF65).
Part of the Half-width and Full-width Forms Unicode block.")

(defconst nskk--kana-hankaku-katakana-end #xFF9F
  "End code point of half-width katakana block (Unicode U+FF9F).")

(defconst nskk--kana-kana-offset 96
  "Code point offset between hiragana and katakana.
A katakana character equals the corresponding hiragana plus this offset.")

;;;; Internal Macros

(defmacro nskk--kana-fill-hash-table (table &rest entries)
  "Fill TABLE with ENTRIES, each entry being a list (KEY VALUE).
Returns TABLE."
  (declare (indent 1) (debug t))
  `(prog1 ,table
     ,@(mapcar (lambda (entry)
                 `(puthash ,(car entry) ,(cadr entry) ,table))
               entries)))

(defmacro nskk--kana-define-range-predicate (name prolog-name start end docstring)
  "Define a character range predicate NAME backed by a Prolog rule.
PROLOG-NAME is the Prolog predicate symbol.
START and END are defconst symbols for the Unicode range boundaries.
DOCSTRING documents the generated ELisp predicate.

Generates:
  - A Prolog rule: (PROLOG-NAME ?c) with arithmetic range check
  - An ELisp predicate (defsubst): (NAME char) => boolean, inlined as
    arithmetic range check under byte-compilation for hot-path performance"
  (declare (indent 1) (debug t))
  `(progn
     (nskk-prolog-<- (,prolog-name \?c)
       (>= \?c ,start)
       (<= \?c ,end))
     (defsubst ,name (char)
       ,docstring
       (and (integerp char)
            (>= char ,start)
            (<= char ,end)))))

;;;; Character Classification Predicates
;;
;; All predicates and their backing Prolog rules are installed at load time.
;; Single-range predicates use `nskk--kana-define-range-predicate'.
;; Multi-range predicates (han, japanese) use direct rule assertions.

(nskk--kana-define-range-predicate
 nskk-kana-hiragana-p kana-hiragana
 nskk--kana-hiragana-start nskk--kana-hiragana-end
 "Return non-nil if CHAR is a hiragana character (U+3040-U+309F).")

(nskk--kana-define-range-predicate
 nskk-kana-katakana-p kana-katakana
 nskk--kana-katakana-start nskk--kana-katakana-end
 "Return non-nil if CHAR is a katakana character (U+30A0-U+30FF).")

(nskk--kana-define-range-predicate
 nskk-kana-hankaku-katakana-p kana-hankaku-katakana
 nskk--kana-hankaku-katakana-start nskk--kana-hankaku-katakana-end
 "Return non-nil if CHAR is a half-width katakana character (U+FF65-U+FF9F).
Half-width katakana are part of the Half-width and Full-width Forms block.")

;; Han (kanji) spans two disjoint Unicode ranges; two Prolog clauses cover both.
(nskk-prolog-<- (kana-han \?c)
  (>= \?c nskk--kana-han-start)
  (<= \?c nskk--kana-han-end))
(nskk-prolog-<- (kana-han \?c)
  (>= \?c nskk--kana-han-extension-a-start)
  (<= \?c nskk--kana-han-extension-a-end))

(defun/k nskk-kana-han-p (char)
  "Return non-nil if CHAR is a han (kanji) character.
Recognizes both CJK Unified Ideographs (U+4E00-U+9FFF) and
CJK Unified Ideographs Extension A (U+3400-U+4DBF)."
  (if (and (integerp char)
           (nskk-prolog-holds-p (list 'kana-han char)))
      (succeed t)
    (fail)))

;; Japanese composite: Prolog disjunction over all four character ranges.
(nskk-prolog-<- (kana-japanese \?c) (kana-hiragana \?c))
(nskk-prolog-<- (kana-japanese \?c) (kana-katakana \?c))
(nskk-prolog-<- (kana-japanese \?c) (kana-han \?c))
(nskk-prolog-<- (kana-japanese \?c) (kana-hankaku-katakana \?c))

(defun/k nskk-kana-japanese-p (char)
  "Return non-nil if CHAR is a Japanese character.
Recognizes the following Unicode ranges:
- Hiragana (U+3040-U+309F)
- Katakana (U+30A0-U+30FF)
- CJK Unified Ideographs (U+4E00-U+9FFF)
- CJK Unified Ideographs Extension A (U+3400-U+4DBF)
- Half-width Katakana (U+FF65-U+FF9F)"
  (if (and (integerp char)
           (nskk-prolog-holds-p (list 'kana-japanese char)))
      (succeed t)
    (fail)))

;;;; Zenkaku/Hankaku Conversion Tables
;;
;; Both Prolog facts and hash table caches are maintained (dual-write pattern).
;; Conversion functions query via `nskk-prolog-query-value' using the
;; `:hash'-indexed `zenkaku-to-hankaku/2' and `hankaku-to-zenkaku/2' facts,
;; which use the hash tables as their backing index.
;; The raw hash tables remain available for external callers.

(defconst nskk--kana-zenkaku-to-hankaku-table
  (let ((table (make-hash-table :test 'equal :size 200)))
    (nskk--kana-fill-hash-table table
      ;; Basic katakana
      ("ア" "ｱ") ("イ" "ｲ") ("ウ" "ｳ") ("エ" "ｴ") ("オ" "ｵ")
      ("カ" "ｶ") ("キ" "ｷ") ("ク" "ｸ") ("ケ" "ｹ") ("コ" "ｺ")
      ("サ" "ｻ") ("シ" "ｼ") ("ス" "ｽ") ("セ" "ｾ") ("ソ" "ｿ")
      ("タ" "ﾀ") ("チ" "ﾁ") ("ツ" "ﾂ") ("テ" "ﾃ") ("ト" "ﾄ")
      ("ナ" "ﾅ") ("ニ" "ﾆ") ("ヌ" "ﾇ") ("ネ" "ﾈ") ("ノ" "ﾉ")
      ("ハ" "ﾊ") ("ヒ" "ﾋ") ("フ" "ﾌ") ("ヘ" "ﾍ") ("ホ" "ﾎ")
      ("マ" "ﾏ") ("ミ" "ﾐ") ("ム" "ﾑ") ("メ" "ﾒ") ("モ" "ﾓ")
      ("ヤ" "ﾔ") ("ユ" "ﾕ") ("ヨ" "ﾖ")
      ("ラ" "ﾗ") ("リ" "ﾘ") ("ル" "ﾙ") ("レ" "ﾚ") ("ロ" "ﾛ")
      ("ワ" "ﾜ") ("ヲ" "ｦ") ("ン" "ﾝ") ("ヴ" "ｳﾞ")
      ;; Dakuten / handakuten combining marks
      ("゛" "ﾞ") ("゜" "ﾟ")
      ;; Small katakana
      ("ァ" "ｧ") ("ィ" "ｨ") ("ゥ" "ｩ") ("ェ" "ｪ") ("ォ" "ｫ")
      ("ッ" "ｯ") ("ャ" "ｬ") ("ュ" "ｭ") ("ョ" "ｮ") ("ヮ" "ﾜ")
      ;; Voiced (dakuten) extended
      ("ガ" "ｶﾞ") ("ギ" "ｷﾞ") ("グ" "ｸﾞ") ("ゲ" "ｹﾞ") ("ゴ" "ｺﾞ")
      ("ザ" "ｻﾞ") ("ジ" "ｼﾞ") ("ズ" "ｽﾞ") ("ゼ" "ｾﾞ") ("ゾ" "ｿﾞ")
      ("ダ" "ﾀﾞ") ("ヂ" "ﾁﾞ") ("ヅ" "ﾂﾞ") ("デ" "ﾃﾞ") ("ド" "ﾄﾞ")
      ("バ" "ﾊﾞ") ("ビ" "ﾋﾞ") ("ブ" "ﾌﾞ") ("ベ" "ﾍﾞ") ("ボ" "ﾎﾞ")
      ;; Semi-voiced (handakuten) extended
      ("パ" "ﾊﾟ") ("ピ" "ﾋﾟ") ("プ" "ﾌﾟ") ("ペ" "ﾍﾟ") ("ポ" "ﾎﾟ")
      ;; Punctuation
      ("。" "｡") ("、" "､") ("・" "･") ("ー" "ｰ")))
  "Hash table (string -> string) mapping zenkaku katakana to hankaku equivalents.")

(defconst nskk--kana-hankaku-to-zenkaku-table
  (let ((table (make-hash-table :test 'equal :size 200)))
    (nskk--kana-fill-hash-table table
      ;; Basic katakana
      ("ｱ" "ア") ("ｲ" "イ") ("ｳ" "ウ") ("ｴ" "エ") ("ｵ" "オ")
      ("ｶ" "カ") ("ｷ" "キ") ("ｸ" "ク") ("ｹ" "ケ") ("ｺ" "コ")
      ("ｻ" "サ") ("ｼ" "シ") ("ｽ" "ス") ("ｾ" "セ") ("ｿ" "ソ")
      ("ﾀ" "タ") ("ﾁ" "チ") ("ﾂ" "ツ") ("ﾃ" "テ") ("ﾄ" "ト")
      ("ﾅ" "ナ") ("ﾆ" "ニ") ("ﾇ" "ヌ") ("ﾈ" "ネ") ("ﾉ" "ノ")
      ("ﾊ" "ハ") ("ﾋ" "ヒ") ("ﾌ" "フ") ("ﾍ" "ヘ") ("ﾎ" "ホ")
      ("ﾏ" "マ") ("ﾐ" "ミ") ("ﾑ" "ム") ("ﾒ" "メ") ("ﾓ" "モ")
      ("ﾔ" "ヤ") ("ﾕ" "ユ") ("ﾖ" "ヨ")
      ("ﾗ" "ラ") ("ﾘ" "リ") ("ﾙ" "ル") ("ﾚ" "レ") ("ﾛ" "ロ")
      ("ﾜ" "ワ") ("ｦ" "ヲ") ("ﾝ" "ン")
      ;; Small katakana
      ("ｧ" "ァ") ("ｨ" "ィ") ("ｩ" "ゥ") ("ｪ" "ェ") ("ｫ" "ォ")
      ("ｯ" "ッ") ("ｬ" "ャ") ("ｭ" "ュ") ("ｮ" "ョ")
      ;; Punctuation
      ("｡" "。") ("､" "、") ("･" "・") ("ｰ" "ー")
      ;; Combining marks
      ("ﾞ" "゛") ("ﾟ" "゜")
      ;; Voiced (dakuten) extended — two-character hankaku sequences
      ("ｶﾞ" "ガ") ("ｷﾞ" "ギ") ("ｸﾞ" "グ") ("ｹﾞ" "ゲ") ("ｺﾞ" "ゴ")
      ("ｻﾞ" "ザ") ("ｼﾞ" "ジ") ("ｽﾞ" "ズ") ("ｾﾞ" "ゼ") ("ｿﾞ" "ゾ")
      ("ﾀﾞ" "ダ") ("ﾁﾞ" "ヂ") ("ﾂﾞ" "ヅ") ("ﾃﾞ" "デ") ("ﾄﾞ" "ド")
      ("ﾊﾞ" "バ") ("ﾋﾞ" "ビ") ("ﾌﾞ" "ブ") ("ﾍﾞ" "ベ") ("ﾎﾞ" "ボ")
      ;; Semi-voiced (handakuten) extended
      ("ﾊﾟ" "パ") ("ﾋﾟ" "ピ") ("ﾌﾟ" "プ") ("ﾍﾟ" "ペ") ("ﾎﾟ" "ポ")
      ;; Voiced u
      ("ｳﾞ" "ヴ")))
  "Hash table (string -> string) mapping hankaku katakana to zenkaku equivalents.
Includes two-character dakuten/handakuten sequences (e.g., \"ｶﾞ\" -> \"ガ\").")

;;;; Character Conversion Functions

(defun/k nskk-kana-hiragana-to-katakana (char)
  "Convert hiragana CHAR to katakana.
Returns the converted character code, or CHAR unchanged if not hiragana."
  (succeed (if (nskk-kana-hiragana-p char)
               (+ char nskk--kana-kana-offset)
             char)))

(defun/k nskk-kana-katakana-to-hiragana (char)
  "Convert katakana CHAR to hiragana.
Returns the converted character code, or CHAR unchanged if not katakana."
  (succeed (if (nskk-kana-katakana-p char)
               (- char nskk--kana-kana-offset)
             char)))

(defun/k nskk--kana-map-string-chars (string converter)
  "Apply CONVERTER to each character in STRING.
Succeeds with the converted string if STRING is a string.
Fails if STRING is not a string."
  (if (stringp string)
      (succeed (apply #'string (mapcar converter (string-to-list string))))
    (fail)))

(defun/k nskk-kana-string-hiragana-to-katakana (string)
  "Convert all hiragana characters in STRING to katakana.
Succeeds with the converted string if STRING is a string.
Fails if STRING is not a string."
  (<- result nskk--kana-map-string-chars string #'nskk-kana-hiragana-to-katakana)
  (succeed result))

(defun/k nskk-kana-string-katakana-to-hiragana (string)
  "Convert all katakana characters in STRING to hiragana.
Succeeds with the converted string if STRING is a string.
Fails if STRING is not a string."
  (<- result nskk--kana-map-string-chars string #'nskk-kana-katakana-to-hiragana)
  (succeed result))

;;;; Zenkaku/Hankaku Conversion Functions

(defun/k nskk--kana-zenkaku-string-to-hankaku (string)
  "Convert zenkaku katakana in STRING to hankaku.
Succeeds with the converted string if STRING is a string.
Fails if STRING is not a string."
  (if (not (stringp string))
      (fail)
    (succeed (cl-loop for char across string
                      for str = (char-to-string char)
                      concat (or (nskk-prolog-query-value
                                  `(zenkaku-to-hankaku ,str \?h) '\?h)
                                 str)))))

(defun/k nskk-kana-zenkaku-to-hankaku (string-or-char)
  "Convert zenkaku katakana STRING-OR-CHAR to hankaku.
For a string, converts each recognized zenkaku character; unrecognized
characters are passed through unchanged.  For a character (integer), returns
the hankaku string equivalent, or a one-character string if unrecognized.
For any other type, returns STRING-OR-CHAR unchanged.
Always succeeds."
  (cond
   ((stringp string-or-char)
    (<- result nskk--kana-zenkaku-string-to-hankaku string-or-char)
    (succeed result))
   ((integerp string-or-char)
    (let* ((str (char-to-string string-or-char))
           (hankaku (nskk-prolog-query-value
                     `(zenkaku-to-hankaku ,str \?h) '\?h)))
      (succeed (or hankaku str))))
   (t
    (succeed string-or-char))))

(defun nskk--kana-hankaku-lookup-at (string i len)
  "Look up hankaku->zenkaku conversion at position I in STRING (length LEN).
Tries the two-character sequence at I and I+1 first (dakuten combinations),
then falls back to the single character at I.  Uses Prolog facts indexed by
`hankaku-to-zenkaku/2'.
Returns a cons (ZENKAKU . ADVANCE) where ADVANCE is 2 (two-char match) or 1."
  (let* ((c1  (char-to-string (aref string i)))
         (two (and (< (1+ i) len)
                   (concat c1 (char-to-string (aref string (1+ i))))))
         (z2  (and two (nskk-prolog-query-value
                        `(hankaku-to-zenkaku ,two \?z) '\?z))))
    (if z2
        (cons z2 2)
      (cons (or (nskk-prolog-query-value `(hankaku-to-zenkaku ,c1 \?z) '\?z) c1)
            1))))

(defun/k nskk--kana-hankaku-string-to-zenkaku (string)
  "Convert hankaku katakana in STRING to zenkaku.
Tries two-character sequences first to handle dakuten combinations.
Succeeds with the converted string if STRING is a string.
Fails if STRING is not a string."
  (if (not (stringp string))
      (fail)
    (let ((parts nil) (i 0) (len (length string)))
      (while (< i len)
        (let ((pair (nskk--kana-hankaku-lookup-at string i len)))
          (push (car pair) parts)
          (setq i (+ i (cdr pair)))))
      (succeed (apply #'concat (nreverse parts))))))

(defun/k nskk-kana-hankaku-to-zenkaku (string-or-char)
  "Convert hankaku katakana STRING-OR-CHAR to zenkaku.
Handles combined dakuten/handakuten marks (e.g., \"ｶﾞ\" -> \"ガ\").
Unrecognized characters are passed through unchanged.
For any other type, returns STRING-OR-CHAR unchanged.
Always succeeds."
  (cond
   ((stringp string-or-char)
    (<- result nskk--kana-hankaku-string-to-zenkaku string-or-char)
    (succeed result))
   ((integerp string-or-char)
    (let* ((str (char-to-string string-or-char))
           (zenkaku (nskk-prolog-query-value
                     `(hankaku-to-zenkaku ,str \?z) '\?z)))
      (succeed (or zenkaku str))))
   (t
    (succeed string-or-char))))

;;;; Prolog Facts Initialization

(defvar nskk--kana-initialized nil
  "Non-nil when zenkaku/hankaku Prolog facts have been populated from hash tables.
Classification predicates and Prolog range rules are asserted at load time.")

(defun/done nskk-kana-initialize ()
  "Populate Prolog facts from the zenkaku/hankaku hash tables.
Classification predicates and Prolog range rules are installed at module
load time; this function only populates the conversion fact tables.
Idempotent: subsequent calls are no-ops."
  (unless nskk--kana-initialized
    (nskk-prolog-set-index 'zenkaku-to-hankaku 2 :hash)
    (nskk-prolog-set-index 'hankaku-to-zenkaku 2 :hash)
    (maphash (lambda (k v)
               (nskk-prolog-assert (list (list 'zenkaku-to-hankaku k v))))
             nskk--kana-zenkaku-to-hankaku-table)
    (maphash (lambda (k v)
               (nskk-prolog-assert (list (list 'hankaku-to-zenkaku k v))))
             nskk--kana-hankaku-to-zenkaku-table)
    ;; Unified kana conversion table: (MODE DIRECTION CONVERTER-FN)
    ;; DIRECTION is `insert' (hiragana → mode script) or `normalize' (mode script → hiragana).
    ;; 3x2 orthogonal table: MODE × DIRECTION → CONVERTER-FN.
    (nskk-prolog-define-fact-table kana-conversion (:arity 3 :index :hash)
      (hiragana      insert      identity)
      (katakana      insert      nskk-kana-string-hiragana-to-katakana)
      (katakana-半角  insert      nskk--hiragana-to-hankaku)
      (hiragana      normalize   identity)
      (katakana      normalize   nskk-kana-string-katakana-to-hiragana)
      (katakana-半角  normalize   nskk--hankaku-to-hiragana))

    (setq nskk--kana-initialized t)))

;;;; Cross-Script Conversion Helpers

(defun nskk--hiragana-to-hankaku (kana)
  "Convert hiragana KANA to half-width katakana via full-width intermediate."
  (nskk-kana-zenkaku-to-hankaku (nskk-kana-string-hiragana-to-katakana kana)))

(defun nskk--hankaku-to-hiragana (text)
  "Convert half-width katakana TEXT to hiragana via full-width intermediate."
  (nskk-kana-string-katakana-to-hiragana (nskk-kana-hankaku-to-zenkaku text)))

(defun nskk-kana-convert-for-mode (kana mode)
  "Convert hiragana KANA to the script of MODE via `kana-conversion/3'."
  (nskk-kana-initialize)
  (funcall (or (nskk-prolog-query-value
                `(kana-conversion ,mode insert \?fn) '\?fn)
               'identity)
           kana))

(defun nskk-kana-normalize-for-lookup (text mode)
  "Normalize MODE-script TEXT to hiragana for dictionary lookup.
Uses the `kana-conversion/3' Prolog fact table for mode dispatch."
  (nskk-kana-initialize)
  (funcall (or (nskk-prolog-query-value
                `(kana-conversion ,mode normalize \?fn) '\?fn)
               'identity)
           text))

(provide 'nskk-kana)

;;; nskk-kana.el ends here
