;;; nskk-converter.el --- Romaji to kana conversion engine -*- lexical-binding: t; -*-

;; Copyright (C) 2026 NSKK Contributors

;; Author: takeokunn <bararararatty@gmail.com>
;; Maintainer: takeokunn <bararararatty@gmail.com>
;; URL: https://github.com/takeokunn/nskk.el
;; Version: 0.1.0
;; Keywords: i18n

;; This file is NOT part of GNU Emacs.
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Romaji-to-kana conversion engine for NSKK (Layer 1: Core Engine).
;;
;; Layer position: L1 (Core Engine) -- depends on nskk-prolog and nskk-custom.
;;
;; Read-only conversion functions (`nskk-converter-lookup', `nskk-converter-convert',
;; `nskk-convert-romaji') are stateless and have no buffer side effects.
;; Style-loading and initialization functions (`nskk-converter-load-style',
;; `nskk-converter-initialize') mutate the Prolog database.
;; All transient conversion state (pending romaji, henkan phase) is managed by the
;; Application layer (nskk-input, nskk-henkan).
;;
;; CPS Variants:
;;
;; All public functions have CPS counterparts with the `/k' suffix, generated by
;; `defun/k' (on-found/on-not-found), `defun/done' (on-done), or `defun/3k'
;; (three explicit continuations, e.g. on-kana/on-partial/on-fail) as appropriate.
;; `defun/3k' is used when the function has three semantically distinct outcomes
;; with no natural default sync-wrapper mapping.  Internal functions
;; `nskk--convert-step/k' and `nskk--convert-step-n/k' are `defun/3k' examples.
;; See `nskk-cps-macros.el' for macro documentation.
;;
;; It handles:
;; - Romaji-to-kana conversion using a Prolog trie longest-match approach
;; - Partial and complete romaji sequence matching
;; - Vowel-based conversion (a, i, u, e, o)
;; - Consonant-vowel combinations (ka, ki, ku, ke, ko, etc.)
;; - Special combinations (sha, shu, sho, cha, chu, cho, etc.)
;; - Small kana and digraph handling
;; - Sokuon (っ) detection: doubled consonant
;; - Hatsuon (ん) detection: n followed by non-vowel/non-y/non-n/non-quote
;;
;; The Prolog trie index (`romaji-to-kana/2') is the authoritative source
;; for all romaji-to-kana mappings.  A parallel `nskk--romaji-table' hash
;; table is maintained as a hot-path cache for O(1) exact-match lookups
;; (used by inline `nskk-converter-lookup'); trie is used for prefix queries.
;;
;; Romaji styles are registered via `nskk-converter-register-style' and
;; loaded on demand.  Standard SKK style is initialized at load time.
;; AZIK style is registered by nskk-azik.el and loaded when configured.

;;;; Prolog Predicates
;;
;; This module maintains the following predicates in the global Prolog database:
;;
;; `romaji-to-kana/2' --- (romaji-to-kana ROMAJI KANA)
;;   Maps a romaji ASCII string to its kana equivalent string.
;;   Indexed with :trie for O(k) prefix lookups (longest-match-first).
;;   ~192 facts; populated by `nskk--initialize-romaji-table'.
;;   Example: (romaji-to-kana "ka" "か")
;;
;; `sokuon-blocker/1' --- (sokuon-blocker CHAR)
;;   Characters that cannot be doubled to produce っ.
;;   Vowels (?a ?i ?u ?e ?o) and ?n are excluded; other consonants trigger
;;   sokuon.  Indexed with :hash for O(1) membership tests.
;;   Populated by `nskk-converter-initialize'.
;;
;; `hatsuon-blocker/1' --- (hatsuon-blocker CHAR)
;;   Characters after n that do not trigger ん insertion.
;;   When the char following n is in this table, n stays in the buffer.
;;   Indexed with :hash for O(1) membership tests.
;;   Populated by `nskk-converter-initialize'.
;;
;; `vowel-char/1' --- (vowel-char CHAR)
;;   The five lowercase romaji vowels: a, i, u, e, o.
;;   Indexed with :hash for O(1) membership tests.
;;   Populated by `nskk-converter-initialize'.
;;
;; `uppercase-vowel-char/1' --- (uppercase-vowel-char CHAR)
;;   The five uppercase romaji vowels: A, I, U, E, O.
;;   Indexed with :hash for O(1) membership tests.
;;   Populated by `nskk-converter-initialize'.

;;; Code:

(require 'cl-lib)
(require 'nskk-cps-macros)
(require 'nskk-prolog)
(require 'nskk-custom)

;; Romaji conversion table
;; Maps romaji sequences to their kana equivalents (as strings for multi-byte)
(defvar nskk--romaji-table
  (make-hash-table :test 'equal :size 200)
  "Romaji to kana conversion table.
Used as a cache by AZIK and for hash-based lookups.  The Prolog trie
is the primary source of truth for `nskk-converter-lookup'.")

(defvar nskk--style-registry '((standard . nskk--initialize-romaji-table))
  "Registry mapping style symbols to their initialization functions.
An alist of the form ((STYLE-SYMBOL . INIT-FN) ...) where INIT-FN is a
zero-argument function that populates the romaji table via
`nskk-converter-add-rule'.  Use `nskk-converter-register-style' to add
entries; do not modify this variable directly.")

(defconst nskk--standard-romaji-rules
  '(;; Vowels
    ("a" "あ") ("i" "い") ("u" "う") ("e" "え") ("o" "お")
    ;; K row
    ("ka" "か") ("ki" "き") ("ku" "く") ("ke" "け") ("ko" "こ")
    ("kya" "きゃ") ("kyu" "きゅ") ("kye" "きぇ") ("kyo" "きょ")
    ;; G row
    ("ga" "が") ("gi" "ぎ") ("gu" "ぐ") ("ge" "げ") ("go" "ご")
    ("gya" "ぎゃ") ("gyu" "ぎゅ") ("gye" "ぎぇ") ("gyo" "ぎょ")
    ;; S row
    ("sa" "さ") ("shi" "し") ("si" "し") ("su" "す") ("se" "せ") ("so" "そ")
    ("sha" "しゃ") ("shu" "しゅ") ("she" "しぇ") ("sho" "しょ")
    ("sya" "しゃ") ("syu" "しゅ") ("sye" "しぇ") ("syo" "しょ")
    ;; Z row
    ("za" "ざ") ("ji" "じ") ("zi" "じ") ("zu" "ず") ("ze" "ぜ") ("zo" "ぞ")
    ("ja" "じゃ") ("ju" "じゅ") ("je" "じぇ") ("jo" "じょ")
    ("zya" "じゃ") ("zyu" "じゅ") ("zye" "じぇ") ("zyo" "じょ")
    ("jya" "じゃ") ("jyu" "じゅ") ("jye" "じぇ") ("jyo" "じょ")
    ;; T row
    ("ta" "た") ("chi" "ち") ("ti" "ち") ("tsu" "つ") ("tu" "つ")
    ("te" "て") ("to" "と")
    ("cha" "ちゃ") ("chu" "ちゅ") ("che" "ちぇ") ("cho" "ちょ")
    ("tya" "ちゃ") ("tyu" "ちゅ") ("tye" "ちぇ") ("tyo" "ちょ")
    ("tsa" "つぁ") ("tsi" "つぃ") ("tse" "つぇ") ("tso" "つぉ")
    ("tha" "てぁ") ("thi" "てぃ") ("thu" "てゅ") ("the" "てぇ") ("tho" "てょ")
    ;; D row
    ("da" "だ") ("di" "ぢ") ("du" "づ") ("de" "で") ("do" "ど")
    ("dya" "ぢゃ") ("dyu" "ぢゅ") ("dye" "ぢぇ") ("dyo" "ぢょ")
    ("dha" "でぁ") ("dhi" "でぃ") ("dhu" "でゅ") ("dhe" "でぇ") ("dho" "でょ")
    ;; N row
    ("na" "な") ("ni" "に") ("nu" "ぬ") ("ne" "ね") ("no" "の")
    ("n'" "ん") ("nn" "ん")
    ("nya" "にゃ") ("nyu" "にゅ") ("nye" "にぇ") ("nyo" "にょ")
    ;; H row
    ("ha" "は") ("hi" "ひ") ("fu" "ふ") ("hu" "ふ") ("he" "へ") ("ho" "ほ")
    ("hya" "ひゃ") ("hyu" "ひゅ") ("hye" "ひぇ") ("hyo" "ひょ")
    ("fa" "ふぁ") ("fi" "ふぃ") ("fe" "ふぇ") ("fo" "ふぉ")
    ;; B row
    ("ba" "ば") ("bi" "び") ("bu" "ぶ") ("be" "べ") ("bo" "ぼ")
    ("bya" "びゃ") ("byu" "びゅ") ("bye" "びぇ") ("byo" "びょ")
    ;; P row
    ("pa" "ぱ") ("pi" "ぴ") ("pu" "ぷ") ("pe" "ぺ") ("po" "ぽ")
    ("pya" "ぴゃ") ("pyu" "ぴゅ") ("pye" "ぴぇ") ("pyo" "ぴょ")
    ;; M row
    ("ma" "ま") ("mi" "み") ("mu" "む") ("me" "め") ("mo" "も")
    ("mya" "みゃ") ("myu" "みゅ") ("mye" "みぇ") ("myo" "みょ")
    ;; Y row
    ("ya" "や") ("yu" "ゆ") ("yo" "よ")
    ;; R row
    ("ra" "ら") ("ri" "り") ("ru" "る") ("re" "れ") ("ro" "ろ")
    ("rya" "りゃ") ("ryu" "りゅ") ("rye" "りぇ") ("ryo" "りょ")
    ;; W row
    ("wa" "わ") ("wo" "を") ("wi" "ゐ") ("we" "ゑ")
    ("wha" "うぁ") ("whi" "うぃ") ("whu" "う") ("whe" "うぇ") ("who" "うぉ")
    ;; V row
    ("va" "ゔぁ") ("vi" "ゔぃ") ("vu" "ゔ") ("ve" "ゔぇ") ("vo" "ゔぉ")
    ("vya" "ゔゃ") ("vyu" "ゔゅ") ("vyo" "ゔょ")
    ;; Small kana
    ("la" "ぁ") ("li" "ぃ") ("lu" "ぅ") ("le" "ぇ") ("lo" "ぉ")
    ("xa" "ぁ") ("xi" "ぃ") ("xu" "ぅ") ("xe" "ぇ") ("xo" "ぉ")
    ("xya" "ゃ") ("xyu" "ゅ") ("xyo" "ょ")
    ("lya" "ゃ") ("lyu" "ゅ") ("lyo" "ょ")
    ("xtsu" "っ") ("xtu" "っ") ("ltsu" "っ") ("ltu" "っ")
    ("xwa" "ゎ") ("xka" "ゕ") ("xke" "ゖ")
    ;; Long vowel mark
    ("-" "ー")
    ;; Basic punctuation
    ("." "。") ("," "、")
    ("[" "「") ("]" "」")
    ;; z-prefix symbols
    ("z-" "〜") ("z." "…") ("z," "‥")
    ("z[" "『") ("z]" "』") ("z/" "・")
    ("zh" "←") ("zj" "↓") ("zk" "↑") ("zl" "→")
    ("z " "　"))
  "Standard SKK romaji-to-kana conversion rules.
Each entry is (ROMAJI KANA) where both are strings.
This data constant is used by `nskk--initialize-romaji-table' to populate
the conversion table, separating rule data from initialization logic.")

(defmacro nskk-converter-define-rules (&rest rule-pairs)
  "Define multiple romaji-to-kana rules at once.
Each element of RULE-PAIRS must be a list (ROMAJI KANA) where ROMAJI and
KANA are string literals.  Expands to a `progn' with one
`nskk-converter-add-rule' call per pair.

Example:
  (nskk-converter-define-rules
    (\"a\" \"あ\")
    (\"i\" \"い\")
    (\"u\" \"う\"))"
  (declare (indent 0) (debug t))
  `(progn
     ,@(mapcar (lambda (pair)
                 `(nskk-converter-add-rule ,(car pair) ,(cadr pair)))
               rule-pairs)))

(defun nskk--initialize-romaji-table ()
  "Populate romaji-to-kana Prolog facts from `nskk--standard-romaji-rules'.
Also populates `nskk--romaji-table' hash table for AZIK and input lookups."
  (dolist (rule nskk--standard-romaji-rules)
    (puthash (car rule) (cadr rule) nskk--romaji-table))
  (nskk-prolog-bulk-facts romaji-to-kana nskk--standard-romaji-rules))

(defun nskk--converter-populate-incomplete-markers ()
  "Populate `nskk--romaji-table' with :incomplete for all proper romaji prefixes.
Auto-derived from the complete romaji entries already in the table."
  (let (keys)
    (maphash (lambda (k _v) (when (stringp k) (push k keys)))
             nskk--romaji-table)
    (dolist (romaji keys)
      (let ((len (length romaji)))
        (dotimes (i (1- len))
          (let ((prefix (substring romaji 0 (1+ i))))
            (unless (gethash prefix nskk--romaji-table)
              (puthash prefix :incomplete nskk--romaji-table))))))))

(defun nskk-converter-lookup (romaji)
  "Look up ROMAJI in the romaji-to-kana conversion system.
Returns kana string if ROMAJI is a complete rule, :incomplete if ROMAJI
is a proper prefix of some rule, or nil if no match.
Uses the hash table for O(1) exact-match lookups (includes both standard
and AZIK rules), falling back to the Prolog trie for prefix detection."
  (when (stringp romaji)
    (let ((result (gethash romaji nskk--romaji-table)))
      (cond
       ((stringp result) result)
       ((eq result :incomplete) :incomplete)
       ((nskk-prolog-trie-has-prefix-p 'romaji-to-kana 2 romaji)
        :incomplete)))))

(defconst nskk--romaji-char-max 127
  "Maximum ASCII character code accepted as romaji input.
Characters above this value (non-ASCII) are never valid romaji and bypass
the sokuon/hatsuon detection logic in `nskk--sokuon-p'.")

(defun/k nskk-convert-romaji (romaji)
  "Convert ROMAJI string to kana by repeatedly applying longest-match conversion.
Returns converted kana string for string input, nil for nil input."
  (succeed (cond
             ((null romaji) nil)
             ((not (stringp romaji)) nil)
             ((zerop (length romaji)) "")
             (t (nskk-convert-romaji--internal (downcase romaji))))))

(defun nskk--sokuon-p (c0 remaining)
  "Return non-nil if C0 and REMAINING qualify as a sokuon (っ) trigger.
C0 is a character integer, typically (aref remaining 0) from the caller.
REMAINING is the unconsumed romaji string; must have length >= 2 for the
doubling check to succeed (length < 2 always returns nil).
Sokuon occurs when C0 is an ASCII consonant not in the `sokuon-blocker' table,
C0 equals the second character of REMAINING, and the two-character pair is
not a complete romaji rule (allowing AZIK entries like \"kk\" -> \"きん\" to
override sokuon via `nskk-converter-lookup')."
  (and (> (length remaining) 1)
       (<= c0 nskk--romaji-char-max)
       (= c0 (aref remaining 1))
       (not (nskk-prolog-holds-p `(sokuon-blocker ,c0)))
       (not (stringp (nskk-converter-lookup (substring remaining 0 2))))))

(defun/3k nskk--convert-step-n (remaining)
    (on-kana on-partial on-fail)
  "Handle n-prefix conversion for REMAINING (which starts with ?n).
ON-KANA is called as (funcall ON-KANA kana rest) when hatsuon produces ん.
ON-PARTIAL and ON-FAIL are forwarded to `nskk-converter-convert/k' when
the n-prefix falls through to the trie (e.g. na, ni, nya)."
  (let ((len (length remaining)))
    (cond
     ;; Standalone n at end
     ((= len 1)
      (funcall on-kana "ん" nil))
     ;; nn -> ん (keep second n for potential next match)
     ((= (aref remaining 1) ?n)
      (funcall on-kana "ん" (if (> len 2) (substring remaining 1) nil)))
     ;; n' -> ん
     ((= (aref remaining 1) ?')
      (funcall on-kana "ん" (if (> len 2) (substring remaining 2) nil)))
     ;; n + non-blocker consonant -> ん + rest
     ((not (nskk-prolog-holds-p `(hatsuon-blocker ,(aref remaining 1))))
      (funcall on-kana "ん" (substring remaining 1)))
     ;; n + vowel/y: fall through to trie lookup (na->な, etc.)
     (t (nskk-converter-convert/k remaining on-kana on-partial on-fail)))))

(defun/3k nskk--convert-step (remaining)
    (on-kana on-partial on-fail)
  "Dispatch one conversion step for REMAINING (must be a non-empty string).
ON-KANA is called as (funcall ON-KANA kana rest) on a successful conversion.
ON-PARTIAL is called as (funcall ON-PARTIAL remaining) when REMAINING is a
known incomplete prefix with no full match yet.
ON-FAIL is called as (funcall ON-FAIL) when REMAINING has no match and is not
a known prefix.
Handles sokuon, hatsuon (via `nskk--convert-step-n/k'), and normal trie lookup
in a flat cond."
  (let ((c0 (aref remaining 0)))
    (cond
     ;; Sokuon: doubled consonant
     ((nskk--sokuon-p c0 remaining)
      (funcall on-kana "っ" (substring remaining 1)))
     ;; n-handling: delegated to nskk--convert-step-n/k
     ((= c0 ?n)
      (nskk--convert-step-n/k remaining on-kana on-partial on-fail))
     ;; Normal: trie longest-match
     (t (nskk-converter-convert/k remaining on-kana on-partial on-fail)))))

(defun nskk--convert-loop/k (remaining parts on-found on-not-found)
  "Tail-recursive conversion loop. [CPS]
REMAINING is the unconsumed input, PARTS is accumulated kana (reversed).
Always calls ON-FOUND with the assembled kana string.
Hand-written explicit pair because ON-FOUND must be passed as a value
to the recursive call (defun/k only rewrites succeed/fail call forms)."
  (if (or (null remaining) (zerop (length remaining)))
      (funcall on-found (apply #'concat (nreverse parts)))
    (nskk--convert-step/k remaining
      (lambda (kana rest)
        (nskk--convert-loop/k
         (and (stringp rest) (> (length rest) 0) rest)
         (cons kana parts)
         on-found on-not-found))
      (lambda (partial)
        (funcall on-found
                 (apply #'concat (nreverse (cons partial parts)))))
      (lambda ()
        (funcall on-found
                 (apply #'concat (nreverse (cons remaining parts))))))))

(defun nskk--convert-loop (remaining parts)
  "Tail-recursive conversion loop (sync wrapper)."
  (nskk--convert-loop/k remaining parts #'identity #'ignore))
(put 'nskk--convert-loop/k 'nskk--cps-continuation-pattern :found-not-found)

(defun/k nskk-convert-romaji--internal (input)
  "Internal romaji conversion via tail-recursive CPS loop.
INPUT must be a non-empty, already-downcased string."
  (succeed (nskk--convert-loop input nil)))

(defun/3k nskk-converter-convert (romaji)
    (on-match on-incomplete on-fail)
  "Convert ROMAJI string to kana via longest-match lookup.
ON-MATCH is called as (funcall ON-MATCH kana remaining) when a complete match
is found; kana is the converted string, remaining is the unconsumed romaji.
ON-INCOMPLETE is called as (funcall ON-INCOMPLETE romaji) when ROMAJI is a
proper prefix of a known sequence (no full match yet).
ON-FAIL is called as (funcall ON-FAIL) when ROMAJI is nil, empty, or has no
match and is not a known prefix.
Uses `nskk-converter-lookup' for each candidate prefix length (4 down to 1)."
  (if (not (and (stringp romaji) (> (length romaji) 0)))
      (funcall on-fail)
    (cl-loop for len from (min 4 (length romaji)) downto 1
             for prefix = (substring romaji 0 len)
             for result = (nskk-converter-lookup prefix)
             when (stringp result)
             return (funcall on-match result (substring romaji len))
             when (eq result :incomplete)
             return (funcall on-incomplete romaji)
             finally return (funcall on-fail))))

(defun nskk-converter-convert (romaji)
  "Convert ROMAJI string to kana.
Returns (kana . remaining-romaji) cons cell on complete match.
Returns (:incomplete . romaji) on partial prefix match.
Returns nil when ROMAJI is nil, empty, or has no match."
  (nskk-converter-convert/k romaji
    #'cons
    (lambda (r) (cons :incomplete r))
    (lambda () nil)))

(defun/k nskk-converter-get-possible-completions (romaji)
  "Get list of possible completions for ROMAJI prefix.
ROMAJI is a string prefix to search.
On success, calls on-found with a list of (romaji . kana) pairs.
On failure (nil/non-string input or no completions), calls on-not-found.
The sync wrapper returns the list on success, nil on failure."
  (if (stringp romaji)
      (let ((result (nskk-prolog-trie-prefix-search 'romaji-to-kana 2 romaji)))
        (if result (succeed result) (fail)))
    (fail)))

(defun/done nskk-converter-add-rule (romaji kana)
  "Add ROMAJI -> KANA mapping to hash table and Prolog database.
Retracts any existing fact for ROMAJI first so overrides replace
the old value in the trie rather than appending a duplicate."
  (puthash romaji kana nskk--romaji-table)
  (when (stringp kana)
    (nskk-prolog-retract (list 'romaji-to-kana romaji '\?_))
    (nskk-prolog-assert (list (list 'romaji-to-kana romaji kana)))))

(defun/done nskk-converter-remove-rule (romaji)
  "Remove ROMAJI from hash table and Prolog database."
  (remhash romaji nskk--romaji-table)
  (nskk-prolog-retract (list 'romaji-to-kana romaji '\?_)))

(defun/k nskk-converter-get-rule (romaji)
  "Return the value mapped to ROMAJI in the conversion table.
On success, calls on-found with the kana string or `:incomplete'.
On failure (key absent), calls on-not-found.
The sync wrapper returns the kana string, `:incomplete', or nil.
Delegates to `nskk-converter-lookup' for unified hash+trie lookup."
  (let ((result (nskk-converter-lookup romaji)))
    (if result (succeed result) (fail))))

(defun/done nskk-converter-register-style (style init-fn)
  "Register INIT-FN as the initialization function for STYLE.
INIT-FN is called with no arguments and should populate the romaji table
via `nskk-converter-add-rule'.  Called for side effects."
  (setf (alist-get style nskk--style-registry) init-fn))

(defun/k nskk-converter-load-style (style)
  "Load romaji rules for STYLE.
Clears existing Prolog facts and repopulates from the registered init function.
Valid styles are defined in `nskk--style-registry'.
On success, calls on-found with the STYLE symbol.
On failure (unregistered STYLE), calls on-not-found with no arguments.
The sync wrapper returns the style symbol on success, or nil for unknown style."
  (let ((init-fn (alist-get style nskk--style-registry)))
    (if init-fn
        (progn
          (clrhash nskk--romaji-table)
          (nskk-prolog-retract-all 'romaji-to-kana 2)
          (nskk-prolog-set-index 'romaji-to-kana 2 :trie)
          (funcall init-fn)
          (nskk--converter-populate-incomplete-markers)
          (succeed style))
      (fail))))

(defmacro nskk-converter-define-style (name docstring &rest rules)
  "Define a new input style NAME with RULES and register it.
DOCSTRING describes the style.  RULES is a list of (ROMAJI KANA) pairs.
Generates an init function `nskk--init-NAME-rules' and registers it under
NAME via `nskk-converter-register-style'.

Example:
  (nskk-converter-define-style my-style
    \"My custom romaji style.\"
    (\"v\" \"ゔ\")
    (\"va\" \"ゔぁ\"))"
  (declare (doc-string 2) (indent 2) (debug (symbolp stringp body)))
  `(progn
     (defun ,(intern (format "nskk--init-%s-rules" name)) ()
       ,docstring
       ,@(mapcar (lambda (rule)
                   `(nskk-converter-add-rule ,(car rule) ,(cadr rule)))
                 rules))
     (nskk-converter-register-style ',name
       ',(intern (format "nskk--init-%s-rules" name)))))

(defvar nskk--converter-initialized nil
  "Non-nil when the romaji-to-kana conversion table has been initialized.")

(defun/done nskk-converter-initialize ()
  "Initialize the romaji-to-kana conversion table.
Idempotent: subsequent calls are no-ops."
  (unless nskk--converter-initialized
    (nskk-converter-load-style 'standard)
    (nskk-prolog-define-fact-table sokuon-blocker (:arity 1 :index :hash)
      (?a) (?i) (?u) (?e) (?o) (?n))
    (nskk-prolog-define-fact-table hatsuon-blocker (:arity 1 :index :hash)
      (?a) (?i) (?u) (?e) (?o) (?y) (?n) (?\'))
    (nskk-prolog-define-fact-table vowel-char (:arity 1 :index :hash)
      (?a) (?i) (?u) (?e) (?o))
    (nskk-prolog-define-fact-table uppercase-vowel-char (:arity 1 :index :hash)
      (?A) (?I) (?U) (?E) (?O))
    (setq nskk--converter-initialized t)))

(provide 'nskk-converter)

;;; nskk-converter.el ends here
