;;; nskk-state.el --- NSKK state management -*- lexical-binding: t; -*-

;; Copyright (C) 2026 NSKK Contributors

;; Author: takeokunn <bararararatty@gmail.com>
;; Maintainer: takeokunn <bararararatty@gmail.com>
;; URL: https://github.com/takeokunn/nskk.el
;; Version: 0.1.0
;; Keywords: i18n

;; This file is NOT part of GNU Emacs.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Buffer-local state management for NSKK (Layer 2: Domain).
;;
;; Layer position: L2 (Domain) -- depends on nskk-prolog and nskk-custom.
;;
;; Manages the per-buffer `nskk-state' struct and the Prolog facts that
;; encode valid modes, valid transitions, and struct slot defaults.
;;
;; Single source of truth: Prolog facts populated by `nskk-state-initialize-prolog'.
;; All mode and phase validation uses live Prolog queries; no Elisp defconsts
;; mirror those facts.
;;
;; The central `nskk-state' struct (cl-defstruct) tracks:
;; - Current input mode: hiragana, katakana, ascii, latin, abbrev,
;;   jisx0208-latin, katakana-半角
;; - Henkan (conversion) phase: nil, on (▽), active (▼), list, registration
;; - Candidate list and selection index
;; - Input and converted text buffers
;; - Conversion start position (henkan-position)
;; - Okurigana consonant (stored as metadata)
;; - Undo/redo stacks
;;
;; State is stored buffer-locally in `nskk-current-state' and mutated
;; exclusively through the setter functions defined in this module.
;; The `nskk-state-set' dispatcher routes mode and henkan-phase changes
;; through validated setters via a flat `pcase' dispatch; all other
;; slots are set inline.
;;
;; Prolog predicates provided by this module:
;; - `mode-properties/5'         -- unified mode descriptor
;;     (mode display-string face help-text cursor-face)
;;     Single source of truth for all mode display data.
;; - `valid-mode/1'              -- derived rule: succeeds iff mode has
;;     a mode-properties/5 fact; used as a guard in transition rules.
;; - `mode-category/2'           -- (mode category) mode classification, derived by japanese-mode/1 rule
;; - `japanese-mode/1'           -- hiragana, katakana, katakana-半角
;; - `valid-henkan-phase/1'      -- membership: nil, on, active, list, registration
;; - `valid-henkan-transition/2' -- (from to) transition graph
;; - `henkan-mode-phase/1'       -- active henkan phases (on, active, list, registration)
;; - `state-slot-default/2'      -- (slot default-value) for struct creation
;;
;; Key public API:
;; - `nskk-state-create'           -- create a new state struct
;; - `nskk-state-get' / `nskk-state-set' -- generic accessor/mutator
;; - `nskk-state-set-SLOT'         -- typed setters (generated by nskk-define-slot-setter)
;; - `nskk-state-valid-mode-p'     -- validate a mode symbol (Prolog query)
;; - `nskk-state-set-henkan-phase' -- validated phase transition (Prolog query)
;; - `nskk-state-force-henkan-phase' -- unvalidated (test/emergency use)
;; - `nskk-state-in-henkan-mode-p' -- test for active conversion
;; - `nskk-state-henkan-on-p'      -- test for ▽ phase
;; - `nskk-state-henkan-active-p'  -- test for ▼ phase
;; - `nskk-state-transition'       -- validated mode switch
;; - `nskk-state-reset'            -- reset to initial values (preserves mode)
;; - `nskk-state-append-input'     -- append char to input buffer
;; - `nskk-state-delete-last-char' -- delete last char from input buffer
;; - `nskk-state-next-candidate' / `nskk-state-previous-candidate'
;;
;; Key public macros (used across 5+ downstream files):
;; - `nskk-with-current-state'   -- guard macro, validates nskk-current-state before body
;; - `nskk-ensure-overlay'       -- creates or returns existing overlay
;; - `nskk-delete-overlay'       -- deletes overlay safely
;; - `nskk-ensure-marker'        -- creates or returns existing marker
;; - `nskk-with-candidates'      -- binds candidate list for body
;;
;; CPS variants (suffix /k) — pass result to continuation; never return a value:
;; - `nskk-state-append-input/k'        -- on-done(new-buf) / on-fail()
;; - `nskk-state-delete-last-char/k'    -- on-deleted(char) / on-empty()
;; - `nskk-state-transition/k'          -- on-found(t) / on-not-found()
;; - `nskk-state-next-candidate/k'      -- on-candidate(cand) / on-empty()
;; - `nskk-state-previous-candidate/k'  -- on-candidate(cand) / on-empty()

;;; Code:

(require 'cl-lib)
(require 'nskk-prolog)
(require 'nskk-custom)
(require 'nskk-cps-macros)

;;;; Internal Macros

(defmacro nskk-with-candidates (state &rest body)
  "Execute BODY only if STATE has non-nil candidates.
Binds `candidates' and `index' for use in BODY."
  (declare (indent 1) (debug t))
  (let ((s (make-symbol "state")))
    `(let ((,s ,state))
       (when (and (nskk-state-p ,s)
                  (nskk-state-candidates ,s))
         (let ((candidates (nskk-state-candidates ,s))
               (index (nskk-state-current-index ,s)))
           ,@body)))))

(defmacro nskk-state-slot-dispatch (state key-sym value &rest slots)
  "Generate cond dispatch for STATE struct slot setters.
KEY-SYM is a symbol being dispatched on, VALUE is the value to set.
SLOTS is a list of slot name symbols (unquoted).

Each slot generates:
  ((eq KEY-SYM \\='SLOT) (setf (nskk-state-SLOT STATE) VALUE) VALUE)
Falls through to nil if no slot matches."
  (declare (indent 3) (debug t))
  (let ((state-sym (make-symbol "state"))
        (val-sym   (make-symbol "val")))
    `(let ((,state-sym ,state)
           (,val-sym   ,value))
       (cond
        ,@(mapcar (lambda (slot)
                    `((eq ,key-sym ',slot)
                      (setf (,(intern (format "nskk-state-%s" slot)) ,state-sym)
                            ,val-sym)
                      ,val-sym))
                  slots)))))

(defmacro nskk-define-slot-setter (slot)
  "Generate sync and CPS setter pair for SLOT in `nskk-state' struct.
Creates two functions:
  `nskk-state-set-SLOT' (state value) -- sync; returns VALUE or nil if invalid
  `nskk-state-set-SLOT/k' (state value on-found on-not-found) -- CPS variant"
  (declare (indent 0) (debug t))
  (let* ((fn      (intern (format "nskk-state-set-%s"   slot)))
         (fn/k    (intern (format "nskk-state-set-%s/k" slot)))
         (accessor (intern (format "nskk-state-%s"       slot))))
    `(progn
       (defun ,fn (state value)
         ,(format "Set %s slot in STATE to VALUE.\nReturns VALUE on success, nil when STATE is not a valid `nskk-state'." slot)
         (when (nskk-state-p state)
           (setf (,accessor state) value)
           value))
       (defun ,fn/k (state value on-found on-not-found)
         ,(format "Set %s slot in STATE to VALUE. [CPS]\nCalls ON-FOUND with VALUE when STATE is valid; ON-NOT-FOUND otherwise." slot)
         (if (nskk-state-p state)
             (progn (setf (,accessor state) value)
                    (funcall on-found value))
           (funcall on-not-found)))
       (put ',fn/k 'nskk--cps-continuation-pattern :found-not-found))))

(declare-function nskk-debug-message "nskk-debug" (format-string &rest args))


;; Main state structure
(cl-defstruct nskk-state
  "Core state structure for NSKK input."
  mode              ;; Current mode (symbol; validated via valid-mode/1 Prolog fact)
  input-buffer      ;; Pending input buffer (string)
  converted-buffer  ;; Converted text buffer (string)
  candidates        ;; List of conversion candidates (list)
  current-index     ;; Current candidate index (integer)
  henkan-position   ;; Position where conversion started (integer or nil)
  marker-position   ;; Cursor position marker (marker or nil)
  previous-mode     ;; Previous mode before current (symbol)
  undo-stack        ;; Undo history stack (list)
  redo-stack        ;; Redo history stack (list)
  henkan-phase      ;; Henkan phase: nil, on (▽), active (▼), list, registration
  metadata)         ;; Additional metadata (plist)

;;;; State Validation Macros

(defmacro nskk-with-state (state &rest body)
  "Execute BODY only if STATE is a valid `nskk-state' struct.
Returns nil if STATE is invalid."
  (declare (indent 1) (debug t))
  `(when (nskk-state-p ,state)
     ,@body))

;;;; Generic Accessor

;; NOTE on nskk-state-get CPS semantics:
;; Many slots (henkan-position, candidates, metadata, marker-position, etc.)
;; have nil as a legitimate value.  Using (if v (succeed v) (fail)) would
;; incorrectly call the not-found continuation for valid nil slot values.
;; Therefore nskk-state-get/k always calls on-found when the accessor exists,
;; even when the slot value is nil.  It calls on-not-found only when STATE is
;; invalid or KEY has no corresponding accessor (fboundp check fails).
(defun/k nskk-state-get (state key)
  "Return the value of KEY slot from STATE struct.
KEY can be a slot name symbol or string.
Returns nil if KEY is not found or STATE is invalid."
  (if (nskk-state-p state)
      (let ((accessor (intern (format "nskk-state-%s" key))))
        (if (fboundp accessor)
            (succeed (funcall accessor state))
          (fail)))
    (fail)))

;;;; Mode Validation — clean pair, no with-no-warnings

(defun nskk-state-valid-mode-p (mode)
  "Return non-nil if MODE is a valid NSKK input mode symbol.
Queries `valid-mode/1' Prolog facts.
Requires `nskk-state-initialize-prolog' to have been called first."
  (nskk-prolog-holds-p `(valid-mode ,mode)))

;;;; Per-Slot Typed Setters (macro-generated)
;;
;; Each call to `nskk-define-slot-setter' generates:
;;   (nskk-state-set-SLOT  state value)             -- sync
;;   (nskk-state-set-SLOT/k state value on-f on-nf) -- CPS
;;
;; Note: `candidates' is intentionally omitted here because the existing
;; `nskk-state-set-candidates' function performs a compound operation
;; (sets candidates AND resets current-index to 0) that callers depend on.
;; That compound function is defined below in the Candidate Management section.

(nskk-define-slot-setter input-buffer)
(nskk-define-slot-setter converted-buffer)
(nskk-define-slot-setter current-index)
(nskk-define-slot-setter henkan-position)
(nskk-define-slot-setter marker-position)
(nskk-define-slot-setter previous-mode)
(nskk-define-slot-setter undo-stack)
(nskk-define-slot-setter redo-stack)
(nskk-define-slot-setter metadata)

;;;; Mode Setter (hand-written, with Prolog validation)

(defun nskk-state-set-mode (state value)
  "Set mode slot in STATE to VALUE with Prolog validation.
Also updates `previous-mode'.  Returns VALUE on success.
Signals an error for invalid mode symbols."
  (when (nskk-state-p state)
    (unless (nskk-state-valid-mode-p value)
      (error "Invalid mode: %s" value))
    (setf (nskk-state-previous-mode state) (nskk-state-mode state)
          (nskk-state-mode state) value)
    value))

;;;; Generic Setter — flat pcase dispatcher

(defun/k nskk-state-set (state key value)
  "Set KEY to VALUE in STATE struct.
KEY can be a slot name symbol or string.
Routes `mode' and `henkan-phase' through validated setters; all other slots
are set directly via `setf'.  Returns VALUE on success."
  (if (not (nskk-state-p state))
      (fail)
    (let ((key-sym (if (stringp key) (intern key) key)))
      (let ((result
             (pcase key-sym
               ('mode         (nskk-state-set-mode state value))
               ('henkan-phase (nskk-state-set-henkan-phase state value))
               ('input-buffer     (setf (nskk-state-input-buffer     state) value) value)
               ('converted-buffer (setf (nskk-state-converted-buffer state) value) value)
               ('candidates       (setf (nskk-state-candidates       state) value) value)
               ('current-index    (setf (nskk-state-current-index    state) value) value)
               ('henkan-position  (setf (nskk-state-henkan-position  state) value) value)
               ('marker-position  (setf (nskk-state-marker-position  state) value) value)
               ('previous-mode    (setf (nskk-state-previous-mode    state) value) value)
               ('undo-stack       (setf (nskk-state-undo-stack       state) value) value)
               ('redo-stack       (setf (nskk-state-redo-stack       state) value) value)
               ('metadata         (setf (nskk-state-metadata         state) value) value)
               (_ nil))))
        (if result (succeed result) (fail))))))

;;;; State Creation

(defun/k nskk-state-create (&optional initial-mode)
  "Create a new NSKK state object with Prolog-sourced slot defaults.
INITIAL-MODE defaults to `nskk-state-default-mode' if not specified.
Slot defaults are queried from `state-slot-default/2' Prolog facts.

NOTE: The generated `nskk-state-create/k' variant places ON-FOUND and
ON-NOT-FOUND after the &optional INITIAL-MODE parameter.  Callers MUST
always pass both continuation arguments explicitly; omitting them causes
a silent nil-continuation crash, because Emacs Lisp `&optional' applies
to all parameters after the first."
  (nskk-state-initialize-prolog)
  (let* ((mode (let ((m (or initial-mode nskk-state-default-mode 'ascii)))
                 (if (nskk-state-valid-mode-p m) m 'ascii)))
         (state (cl-flet ((default (slot)
                            (nskk-prolog-query-value
                             `(state-slot-default ,slot \?v) '\?v)))
                  (make-nskk-state
                   :mode             mode
                   :input-buffer     (default 'input-buffer)
                   :converted-buffer (default 'converted-buffer)
                   :candidates       (default 'candidates)
                   :current-index    (default 'current-index)
                   :henkan-position  (default 'henkan-position)
                   :marker-position  (default 'marker-position)
                   :previous-mode    mode
                   :undo-stack       (default 'undo-stack)
                   :redo-stack       (default 'redo-stack)
                   :henkan-phase     (default 'henkan-phase)
                   :metadata         (default 'metadata)))))
    (succeed state)))

;;;; Henkan Phase Predicates — clean pairs, no with-no-warnings

(defun nskk-state-in-henkan-mode-p (state)
  "Return non-nil if STATE is currently in an active conversion phase.
Queries `henkan-mode-phase/1' Prolog facts."
  (and (nskk-state-p state)
       (nskk-prolog-holds-p `(henkan-mode-phase ,(nskk-state-henkan-phase state)))))

(defun/k nskk-state-henkan-on-p (state)
  "Check if STATE is in henkan-on phase (▽)."
  (if (and (nskk-state-p state)
           (eq (nskk-state-henkan-phase state) 'on))
      (succeed t)
    (fail)))

(defun/k nskk-state-henkan-active-p (state)
  "Check if STATE is in henkan-active phase (▼)."
  (if (and (nskk-state-p state)
           (eq (nskk-state-henkan-phase state) 'active))
      (succeed t)
    (fail)))

;;;; Henkan Phase Setter — clean pair, no with-no-warnings, no nested condition-case

(defun nskk-state-set-henkan-phase (state phase)
  "Set henkan PHASE in STATE with Prolog-validated transition.
Validates PHASE against `valid-henkan-phase/1' and the current phase
against `valid-henkan-transition/2'.  Same-phase transitions are no-ops.
Signals an error for invalid phase or invalid transition."
  (unless (nskk-state-p state)
    (error "nskk-state-set-henkan-phase: STATE must be an nskk-state, got %S" state))
  (unless (nskk-prolog-holds-p `(valid-henkan-phase ,phase))
    (error "Invalid henkan phase: %s (not in valid-henkan-phase/1)" phase))
  (let ((current (nskk-state-henkan-phase state)))
    (unless (or (eq current phase)
                (nskk-prolog-holds-p `(valid-henkan-transition ,current ,phase)))
      (error "Invalid henkan phase transition: %s -> %s" current phase)))
  (setf (nskk-state-henkan-phase state) phase))

(defun/done nskk-state-force-henkan-phase (state phase)
  "Force set henkan PHASE in STATE, bypassing transition validation.
Validates PHASE via `valid-henkan-phase/1' Prolog fact.
Use for test setup or emergency reset."
  (nskk-with-state state
    (unless (nskk-prolog-holds-p `(valid-henkan-phase ,phase))
      (error "Invalid henkan phase: %s (not in valid-henkan-phase/1)" phase))
    (setf (nskk-state-henkan-phase state) phase)))

;;;; State Transition

(defun/k nskk-state-transition (state from-mode to-mode)
  "Transition STATE from FROM-MODE to TO-MODE.
Validates that TO-MODE is a valid mode via `valid-mode/1' Prolog fact.
Calls on-found with t on success; on-not-found on failure."
  (let ((ok (nskk-with-state state
               (when (and (eq (nskk-state-mode state) from-mode)
                          (nskk-state-valid-mode-p to-mode))
                 (setf (nskk-state-previous-mode state) from-mode
                       (nskk-state-mode state)          to-mode)
                 t))))
    (if ok (succeed t) (fail))))

;;;; State Reset

(defun/done nskk-state-reset (state)
  "Reset STATE to initial state (preserves mode and previous-mode).
Slot defaults are sourced from `state-slot-default/2' Prolog facts."
  (nskk-with-state state
    (cl-flet ((default (slot)
                (nskk-prolog-query-value `(state-slot-default ,slot \?v) '\?v)))
      (setf (nskk-state-input-buffer     state) (default 'input-buffer)
            (nskk-state-converted-buffer state) (default 'converted-buffer)
            (nskk-state-candidates       state) (default 'candidates)
            (nskk-state-current-index    state) (default 'current-index)
            (nskk-state-henkan-position  state) (default 'henkan-position)
            (nskk-state-marker-position  state) (default 'marker-position)
            (nskk-state-undo-stack       state) (default 'undo-stack)
            (nskk-state-redo-stack       state) (default 'redo-stack)
            (nskk-state-metadata         state) (default 'metadata)))
    (nskk-state-force-henkan-phase state nil)))

;;;; Buffer Management Helpers

(defun/k nskk-state-append-input (state char)
  "Append CHAR to STATE's input buffer.
CHAR must be a valid character (integer).
Returns the new buffer string on success, nil on failure.
Uses `concat' with a list to avoid intermediate string allocation."
  (if (and (nskk-state-p state) (characterp char))
      (let ((buf (nskk-state-input-buffer state)))
        (unless (stringp buf)
          (setq buf ""))
        (let ((new-buf (concat buf (list char))))
          (setf (nskk-state-input-buffer state) new-buf)
          (succeed new-buf)))
    (fail)))

(defun/k nskk-state-delete-last-char (state)
  "Delete last character from STATE's input buffer.
Returns the deleted character on success, nil if buffer is empty
or state is invalid.
Properly handles multibyte characters."
  (if (nskk-state-p state)
      (let ((buf (nskk-state-input-buffer state)))
        (if (and (stringp buf) (> (length buf) 0))
            (let ((last-char (aref buf (1- (length buf))))
                  (new-buf (substring buf 0 (1- (length buf)))))
              (setf (nskk-state-input-buffer state) new-buf)
              (succeed last-char))
          (fail)))
    (fail)))

(defun/done nskk-state-clear-input (state)
  "Clear STATE's input buffer.
Returns t on success, nil if state is invalid."
  (nskk-with-state state
    (setf (nskk-state-input-buffer state) "")))

;;;; Candidate Management Helpers

(defun/done nskk-state-set-candidates (state candidates)
  "Set CANDIDATES list in STATE and reset the current index to 0."
  (nskk-with-state state
    (setf (nskk-state-candidates state) candidates
          (nskk-state-current-index state) 0)))

(defun/k nskk-state-next-candidate (state)
  "Move to next candidate in STATE.
Returns current candidate or nil if no candidates."
  (if (and (nskk-state-p state)
           (nskk-state-candidates state))
      (let* ((candidates (nskk-state-candidates state))
             (index (nskk-state-current-index state)))
        (setf (nskk-state-current-index state)
              (mod (1+ index) (length candidates)))
        (succeed (nth (nskk-state-current-index state) candidates)))
    (fail)))

(defun/k nskk-state-previous-candidate (state)
  "Move to previous candidate in STATE.
Returns current candidate or nil if no candidates."
  (if (and (nskk-state-p state)
           (nskk-state-candidates state))
      (let* ((candidates (nskk-state-candidates state))
             (index (nskk-state-current-index state)))
        (setf (nskk-state-current-index state)
              (mod (1- index) (length candidates)))
        (succeed (nth (nskk-state-current-index state) candidates)))
    (fail)))

(defun/k nskk-state-current-candidate (state)
  "Return the currently selected candidate from STATE, or nil if none."
  (if (and (nskk-state-p state)
           (nskk-state-candidates state))
      (succeed (nth (nskk-state-current-index state)
                    (nskk-state-candidates state)))
    (fail)))

;;;; Metadata Helpers

(defmacro nskk-define-metadata-setter (field &optional docstring)
  "Define `nskk-state-set-FIELD' as a metadata setter for FIELD.
FIELD is a symbol naming the metadata key and the suffix of the
generated function name.
Optional DOCSTRING overrides the default documentation string.
Generated function signature: (nskk-state-set-FIELD state value)"
  (declare (indent 1) (debug t))
  (let* ((fname (intern (format "nskk-state-set-%s" field)))
         (doc (or docstring
                  (format "Set %s in STATE metadata to VALUE." field))))
    `(defun ,fname (state value)
       ,doc
       (nskk-with-state state
         (nskk-state-put-metadata state ',field value)))))

(defun/k nskk-state-get-metadata (state key)
  "Return the value of metadata KEY from STATE's metadata plist."
  (if (nskk-state-p state)
      (succeed (plist-get (nskk-state-metadata state) key))
    (fail)))

(defun/done nskk-state-put-metadata (state key value)
  "Set metadata KEY to VALUE in STATE's metadata plist."
  (nskk-with-state state
    (setf (nskk-state-metadata state)
          (plist-put (nskk-state-metadata state) key value))))

;; Additional state setters for layer integration
(nskk-define-metadata-setter remaining-romaji)
(nskk-define-metadata-setter kana-type)
(nskk-define-metadata-setter width-type)
(nskk-define-metadata-setter okurigana
  "Set okurigana in STATE metadata to VALUE.
VALUE should be the okurigana consonant (e.g., \\='k\\=' for \\='く\\=').")

(defun/k nskk-state-get-okurigana (state)
  "Return the okurigana consonant from STATE's metadata, or nil if unset."
  (if (nskk-state-p state)
      (progn
        (<- val nskk-state-get-metadata state 'okurigana)
        (succeed val))
    (fail)))

;;;; Buffer-local State Management

(defvar-local nskk-current-state nil
  "Buffer-local NSKK state object for the current buffer.")

(defmacro nskk-with-current-state (&rest body)
  "Execute BODY with `nskk-current-state' validated.
Binds nothing extra; simply guards against nil/invalid state."
  (declare (indent 0) (debug t))
  `(when (and (boundp 'nskk-current-state)
              (nskk-state-p nskk-current-state))
     ,@body))

(defun/k nskk-state-get-mode ()
  "Return the current NSKK input mode symbol from `nskk-current-state'.
Returns nil when no state is active in the current buffer."
  (if (and (boundp 'nskk-current-state)
           (nskk-state-p nskk-current-state))
      (succeed (nskk-state-mode nskk-current-state))
    (fail)))

;;;; Shared Buffer-Local State

(defvar-local nskk--romaji-buffer ""
  "Buffer for accumulating romaji input before conversion to kana.")

(defvar-local nskk--conversion-start-marker nil
  "Marker for the position where conversion (henkan) input started.
Set when the user types an uppercase letter in Japanese mode to begin
composing a word for conversion.  This replaces the use of `mark' for
SKK conversion tracking, so that SKK does not interfere with the
Emacs mark ring.")

(defvar-local nskk--conversion-overlay nil
  "Overlay for displaying converted text.")

(defvar-local nskk--pending-romaji-overlay nil
  "Overlay for displaying pending/incomplete romaji input.
Unlike `nskk--conversion-overlay' which uses the \\='display property on a
real buffer range, this overlay uses \\='after-string on a zero-length overlay
at point -- no buffer text exists yet for the incomplete romaji sequence.")

(defvar-local nskk--candidate-overlay nil
  "Overlay for candidate list display (Phase 2: list selection mode).
Zero-length overlay anchored at the end of the conversion overlay.
Managed by `nskk-candidate-window.el'; declared here following the
project convention that all buffer-local overlay variables live in
nskk-state.el alongside `nskk--conversion-overlay' and
`nskk--pending-romaji-overlay'.")

(defvar-local nskk--dcomp-multiple-overlay nil
  "Overlay for displaying multiple dynamic completion candidates inline.
Zero-length overlay anchored at the end of the preedit text.
Managed by dcomp-multiple display logic in nskk-henkan.el; declared here
following the project convention that all buffer-local overlay variables
live in nskk-state.el.")

;;;; Overlay and Marker Management Macros

(defmacro nskk-ensure-overlay (var start end &rest props)
  "Move or create an overlay for VAR covering START to END in the current buffer.
Reuses VAR's existing overlay object if it satisfies `overlayp', creating
a new one otherwise.  In both cases the overlay is moved to START..END and
any PROPS (a plist of property value pairs) are applied via `overlay-put'.
VAR is mutated via `setq' when a new overlay is created."
  (declare (indent 2) (debug t))
  `(progn
     (if (overlayp ,var)
         (move-overlay ,var ,start ,end (current-buffer))
       (setq ,var (make-overlay ,start ,end)))
     (cl-loop for (prop val) on (list ,@props) by #'cddr
              do (overlay-put ,var prop val))))

(defmacro nskk-delete-overlay (var)
  "Delete the overlay in VAR and set VAR to nil.
Safe to call when VAR is nil or not an overlay (idempotent)."
  (declare (indent 0) (debug t))
  `(when (overlayp ,var)
     (delete-overlay ,var)
     (setq ,var nil)))

(defmacro nskk-ensure-marker (var pos)
  "Move or create a marker for VAR positioned at POS in the current buffer.
Creates a new marker and assigns it to VAR via `setq' if VAR is not
already a marker.  In both cases the marker is moved to POS unconditionally."
  (declare (indent 0) (debug t))
  `(progn
     (unless (markerp ,var)
       (setq ,var (make-marker)))
     (set-marker ,var ,pos (current-buffer))))

(defvar-local nskk--henkan-count 0
  "Number of times SPC has been pressed during current conversion.")

(defvar-local nskk--registration-depth 0
  "Current nesting depth of dictionary registration.")

(defvar nskk--state-prolog-initialized nil
  "Non-nil when state machine Prolog predicates have been initialized.")

(defun/done nskk-state-initialize-prolog ()
  "Initialize NSKK state machine Prolog predicates (idempotent).
Subsequent calls are no-ops guarded by `nskk--state-prolog-initialized'."
  (unless nskk--state-prolog-initialized
    ;; Unified mode properties
    ;; mode-properties/5: (MODE DISPLAY-STRING FACE HELP-TEXT CURSOR-FACE)
    ;; NOTE: Faces (nskk-modeline-*-face) are defined in nskk-modeline.el, which
    ;; is loaded after nskk-state.el.  Prolog facts store the face symbols as
    ;; data—they are not evaluated at assertion time, so forward references are safe.
    ;; Similarly, cursor face symbols are stored as data and dereferenced via
    ;; `face-attribute' at runtime (see `nskk--cursor-with-color' in nskk-modeline.el).
    (nskk-prolog-define-fact-table mode-properties (:arity 5 :index :hash)
      (hiragana "かな" nskk-modeline-hiragana-face
                "Hiragana input mode" nskk-cursor-hiragana)
      (katakana "カナ" nskk-modeline-katakana-face
                "Katakana input mode" nskk-cursor-katakana)
      (katakana-半角 "ｶﾅ" nskk-modeline-katakana-face
                   "Half-width katakana input mode" nskk-cursor-katakana)
      (abbrev "aA" nskk-modeline-abbrev-face
              "Abbreviation mode" nskk-cursor-abbrev)
      (ascii "SKK" nskk-modeline-direct-face
             "Direct/ASCII input mode" nskk-cursor-latin)
      (latin "SKK" nskk-modeline-direct-face
             "Direct/ASCII input mode" nskk-cursor-latin)
      (jisx0208-latin "全英" nskk-modeline-jisx0208-latin-face
                      "Full-width latin input mode" nskk-cursor-jisx0208-latin))

    ;; valid-mode/1: derived rule — a symbol is a valid mode iff it has a mode-properties fact.
    ;; Uses distinct variable names (?disp, ?face, ?help, ?cur) to avoid
    ;; spurious unification failures that occur with repeated ?_ names.
    (nskk-prolog-<- (valid-mode \?m)
      (mode-properties \?m \?disp \?face \?help \?cur))

    ;; Mode category: orthogonal classification of input modes.
    ;; `japanese'     — hiragana/katakana/katakana-半角
    ;; `marker-mode'  — modes using a conversion-start marker (abbrev)
    ;; `other'        — direct input modes (ascii/latin/jisx0208-latin)
    (nskk-prolog-define-fact-table mode-category (:arity 2 :index :hash)
      (hiragana      japanese)
      (katakana      japanese)
      (katakana-半角  japanese)
      (abbrev        marker-mode)
      (ascii         other)
      (latin         other)
      (jisx0208-latin other))

    ;; japanese-mode/1: derived from mode-category/2.
    ;; A mode is a Japanese input mode iff its category is `japanese'.
    (nskk-prolog-<- (japanese-mode \?m) (mode-category \?m japanese))

    ;; Valid henkan phases
    (nskk-prolog-define-fact-table valid-henkan-phase (:arity 1 :index :hash)
      (nil)
      (on)
      (active)
      (list)
      (registration))

    ;; Henkan phase transition graph
    (nskk-prolog-define-fact-table valid-henkan-transition (:arity 2 :index :hash)
      (nil on)
      (on active)
      (on registration)
      (on nil)
      (active on)
      (active nil)
      (active list)
      (list on)
      (list nil)
      (list registration)
      (registration nil)
      (registration list))

    ;; Henkan mode phase classification
    (nskk-prolog-define-fact-table henkan-mode-phase (:arity 1 :index :hash)
      (on)
      (active)
      (list)
      (registration))

    ;; State slot defaults
    (nskk-prolog-define-fact-table state-slot-default (:arity 2 :index :hash)
      (input-buffer "")
      (converted-buffer "")
      (candidates nil)
      (current-index 0)
      (henkan-position nil)
      (marker-position nil)
      (undo-stack nil)
      (redo-stack nil)
      (henkan-phase nil)
      (metadata nil))

    (setq nskk--state-prolog-initialized t)))

(provide 'nskk-state)

;;; nskk-state.el ends here
