;;; nskk-debug.el --- NSKK unified debug mode -*- lexical-binding: t; -*-

;; Copyright (C) 2026 NSKK Contributors

;; Author: takeokunn <bararararatty@gmail.com>
;; Maintainer: takeokunn <bararararatty@gmail.com>
;; URL: https://github.com/takeokunn/nskk.el
;; Keywords: i18n convenience

;; This file is NOT part of GNU Emacs.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; NSKK unified debug mode.

;;; Code:

(require 'nskk-cps-macros)
(require 'nskk-prolog)
(require 'nskk-custom)

;;;; Prolog Facts
;;
;; Config facts for buffer/format constants.  These are the authoritative
;; source; the `defconst' forms below are derived from them via query.

(nskk-prolog-assert '((debug-buffer-name "*NSKK Debug*")))
(nskk-prolog-assert '((debug-timestamp-fmt "%H:%M:%S.%3N")))
(nskk-prolog-assert '((debug-message-fmt "[%s] %s\n")))

;;;; Data

(defconst nskk--debug-buffer-name
  (nskk-prolog-query-value '(debug-buffer-name \?Name) '\?Name)
  "Name of the NSKK debug buffer.")

(defconst nskk--debug-timestamp-format
  (nskk-prolog-query-value '(debug-timestamp-fmt \?Fmt) '\?Fmt)
  "Format string for debug log timestamps.")

(defconst nskk--debug-message-format
  (nskk-prolog-query-value '(debug-message-fmt \?Fmt) '\?Fmt)
  "Format string for a complete debug log entry.
The first %s is the timestamp, the second %s is the message text.")

;;;; CPS Helper: safe format with error recovery
;;
;; Hand-written rather than generated by `defun/k', because `condition-case'
;; is not in the CPS AST dispatch table.  Only the `format' call sits inside
;; `condition-case': an error raised by ON-FOUND must reach the caller rather
;; than be absorbed as if the format string had failed.

(defun nskk--debug-format/k (format-string args on-found on-not-found)
  "Format FORMAT-STRING with ARGS list.
Calls ON-FOUND with the formatted string on success.
Calls ON-NOT-FOUND on format error, after issuing a `display-warning'.  [CPS]"
  (let* ((format-error nil)
         (formatted
          (condition-case err
              (apply #'format format-string args)
            (error
             (setq format-error err)
             nil))))
    (cond
     (format-error
      (display-warning 'nskk
                       (format "Debug logging error: %s"
                               (error-message-string format-error))
                       :warning)
      (funcall on-not-found))
     (t
      (funcall on-found formatted)))))

;; `eval-and-compile' because the `<-' forms below read this property while
;; this file is being byte-compiled; a plain `put' runs only at load time and
;; would leave the pattern unset for the whole compilation.
(eval-and-compile
  (put 'nskk--debug-format/k 'nskk--cps-continuation-pattern :found-not-found))

;;;; Buffer Management

(defun nskk--debug-buffer ()
  "Get or create the NSKK debug buffer."
  (or (get-buffer nskk--debug-buffer-name)
      (let ((buffer (get-buffer-create nskk--debug-buffer-name)))
        (with-current-buffer buffer
          (special-mode))
        buffer)))

(defun/done nskk--debug-trim ()
  "Trim the debug buffer to at most `nskk-debug-max-entries' lines.
Must be called with the debug buffer current."
  (let ((inhibit-read-only t))
    (goto-char (point-max))
    (forward-line (- nskk-debug-max-entries))
    (when (> (point) (point-min))
      (delete-region (point-min) (point)))))

(defun/k nskk--debug-append (message)
  "Append MESSAGE to the debug buffer with a timestamp prefix."
  (with-current-buffer (nskk--debug-buffer)
    (let ((inhibit-read-only t))
      (goto-char (point-max))
      (insert (format nskk--debug-message-format
                      (format-time-string nskk--debug-timestamp-format)
                      message))
      (nskk--debug-trim)))
  (succeed message))

;;;; Logging Functions

(defun/k nskk-debug-log (format-string &rest args)
  "Log a message with a timestamp when debug is enabled.
FORMAT-STRING is passed to `format' with ARGS.
ARGS are evaluated even when debug is disabled, so guard expensive
expressions with `(when nskk-debug-enabled (nskk-debug-log ...))'."
  (when (bound-and-true-p nskk-debug-enabled)
    (<- result nskk--debug-append (apply #'format format-string args))
    (succeed result)))

(defun/k nskk-debug-message (format-string &rest args)
  "Log a debug message, absorbing any format error.
FORMAT-STRING and ARGS are passed to `format'.
A malformed FORMAT-STRING issues a warning and logs nothing, where
`nskk-debug-log' would signal, so this is safe to call from error
handlers.  ARGS are evaluated even when debug is disabled."
  (when (bound-and-true-p nskk-debug-enabled)
    (<- msg nskk--debug-format format-string args)
    (<- result nskk--debug-append msg)
    (succeed result)))

;;;; Interactive Commands

(defun/done nskk-debug-toggle ()
  "Toggle NSKK debug mode."
  :interactive t
  (setq nskk-debug-enabled (not nskk-debug-enabled))
  (message "NSKK debug mode is %s"
           (if nskk-debug-enabled "enabled" "disabled")))

(defun/done nskk-debug-show ()
  "Show the NSKK debug buffer."
  :interactive t
  (display-buffer (nskk--debug-buffer)))

(defun/done nskk-debug-clear ()
  "Clear the NSKK debug buffer."
  :interactive t
  (let ((buf (get-buffer nskk--debug-buffer-name))
        (inhibit-read-only t))
    (when buf
      (with-current-buffer buf
        (erase-buffer))))
  (message "NSKK debug buffer is cleared"))

(nskk-debug-log "NSKK debug module loaded")

(provide 'nskk-debug)

;;; nskk-debug.el ends here
