;;; nskk-test-macros-test.el --- Property test harness tests -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'nskk-test-macros)

(defun nskk-test-macros--property-body (macro property seed)
  "Return the test body generated by MACRO for PROPERTY and SEED."
  (let ((definition
         (macroexpand-1
          `(,macro harness-probe ((sample integer)) ,property 16 ,seed))))
    (eval `(lambda () ,@(cdddr definition)) t)))

(ert-deftest nskk-test-macros-fixed-seed-replays-generated-values ()
  (dolist (macro '(nskk-property-test-seeded
                   nskk-property-test-with-shrinking))
    (dolist (seed '(42 123456 0))
      (let ((body (nskk-test-macros--property-body macro t seed))
            sequences)
        (dolist (ambient '("ambient-a" "ambient-b"))
          (random ambient)
          (let (samples)
            (cl-letf (((symbol-function 'nskk-generate)
                       (lambda (_generator)
                         (let ((value (random 1000000)))
                           (push value samples)
                           value))))
              (funcall body))
            (should (= (length samples) 16))
            (push samples sequences)))
        (should (equal (car sequences) (cadr sequences)))))))

(ert-deftest nskk-test-macros-false-properties-fail ()
  (dolist (macro '(nskk-property-test-seeded
                   nskk-property-test-with-shrinking))
    (let ((body (nskk-test-macros--property-body macro nil 42)))
      (cl-letf (((symbol-function 'nskk-generate)
                 (lambda (_generator) 8)))
        (should-error (funcall body) :type 'ert-test-failed)))))

(ert-deftest nskk-test-macros-seed-override-replays-generated-values ()
  (dolist (macro '(nskk-property-test-seeded
                   nskk-property-test-with-shrinking))
    (dolist (seed '(42 0))
      (let ((body (nskk-test-macros--property-body macro t nil))
            (nskk-test-random-seed seed)
            sequences)
        (dolist (ambient '("ambient-a" "ambient-b"))
          (random ambient)
          (let (samples)
            (cl-letf (((symbol-function 'nskk-generate)
                       (lambda (_generator)
                         (let ((value (random 1000000)))
                           (push value samples)
                           value))))
              (funcall body))
            (should (= (length samples) 16))
            (push samples sequences)))
        (should (equal (car sequences) (cadr sequences)))))))

(provide 'nskk-test-macros-test)
;;; nskk-test-macros-test.el ends here
