;;; nskk-e2e-dcomp.el --- E2E dynamic completion tests for NSKK  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 NSKK Contributors

;; Author: takeokunn <bararararatty@gmail.com>
;; Maintainer: takeokunn <bararararatty@gmail.com>
;; URL: https://github.com/takeokunn/nskk.el
;; Keywords: i18n, testing

;; This file is NOT part of GNU Emacs.

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; E2E tests for dynamic completion (dcomp) via TAB key (DDSKK §5.3).
;;
;; Architecture:
;;   Dynamic completion works in preedit (▽) state.  When the user presses
;;   TAB, `nskk-dcomp-complete' searches the dictionary for all entries whose
;;   reading key starts with the current preedit reading, then replaces the
;;   reading with the first match.  Repeated TAB presses cycle through all
;;   matching entries in definition order.  When no match exists, TAB is a
;;   no-op (the preedit reading is unchanged).
;;
;; Verification API:
;;   `nskk-preedit-string' -- returns the current preedit reading text without
;;   the ▽ or ▼ marker, e.g. "かんじ" while ▽かんじ is displayed.
;;   `nskk-current-mode'   -- returns the current NSKK mode symbol, e.g.
;;   \\='hiragana.  Tab must never change the mode.
;;
;; Dictionary prefix design:
;;   `nskk-e2e--dcomp-dict' has three entries all sharing the prefix "かん",
;;   so a preedit of "かん" (typed as "Kan") has exactly three completions.
;;   `nskk-e2e--dcomp-dict-extended' adds two more entries with distinct
;;   two-character prefixes ("さく" and "にほ") to cover table tests for
;;   prefixes outside the かん cluster.
;;
;; PBT crash-freedom property:
;;   For any romaji string generated by the `romaji-basic' generator, typing
;;   that string followed by TAB must not raise an unhandled error.  The
;;   preedit must remain a string and the mode must remain \\='hiragana.

;;; Code:

(require 'ert)
(require 'nskk-e2e-helpers)
(require 'nskk-test-macros)
(require 'nskk-pbt-generators)

;;;;
;;;; Test Dictionaries
;;;;

(defconst nskk-e2e--dcomp-dict
  '(("かんじ"  . ("漢字"))
    ("かんが"  . ("考え"))
    ("かんしゃ" . ("感謝")))
  "Dictionary entries for dynamic completion tests.
All three readings share the prefix \"かん\" to exercise prefix-based completion.")

(defconst nskk-e2e--dcomp-dict-extended
  '(("かんじ"  . ("漢字"))
    ("かんが"  . ("考え"))
    ("かんしゃ" . ("感謝"))
    ("さくら"  . ("桜"))
    ("にほん"  . ("日本")))
  "Extended dictionary for dcomp table tests.
Adds \"さくら\" and \"にほん\" to cover prefixes outside the \"かん\" cluster.")

;;;;
;;;; Original 3 Tests (preserved exactly)
;;;;

(nskk-describe "dynamic completion via Tab key (動的補完)"
  (nskk-it "Tab in preedit completes reading from dictionary prefix"
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      ;; "Kan" → ▽かん (partial reading, prefix of かんじ / かんが / かんしゃ).
      (nskk-e2e-type "Kan")
      ;; Tab should complete to the first dict key matching prefix "かん".
      (nskk-e2e-type "TAB")
      ;; Still in preedit (▽) phase — completion extends the reading, not converts.
      (nskk-e2e-assert-henkan-phase 'on)
      ;; Reading has been extended; e.g., preedit now shows ▽かんじ.
      ;; (Exact first completion order is implementation-defined.)
      (should (> (length (nskk-preedit-string)) (length "かん")))))

  (nskk-it "repeated Tab cycles through all completions"
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      ;; First Tab → first completion (e.g., かんじ).
      (nskk-e2e-type "TAB")
      (let ((first-completion (nskk-preedit-string)))
        ;; Second Tab → next completion (e.g., かんが).
        (nskk-e2e-type "TAB")
        (let ((second-completion (nskk-preedit-string)))
          ;; Completions must be distinct.
          (should-not (equal first-completion second-completion))))))

  (nskk-it "Tab with no matching prefix does not change preedit"
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      ;; "Xyz" → ▽ (no such prefix in dict).
      (nskk-e2e-type "Xyz")
      (let ((reading-before (nskk-preedit-string)))
        ;; Tab should be a no-op (or ring the bell) when no completions exist.
        (nskk-e2e-type "TAB")
        ;; Preedit must be unchanged.
        (should (equal reading-before (nskk-preedit-string)))
        ;; Still in preedit phase.
        (nskk-e2e-assert-henkan-phase 'on)))))

;;;;
;;;; Table-Driven Tests: prefix → minimum extended reading length
;;;;

;; Tables split by dict to avoid passing a symbol reference as a column value
;; (nskk-deftest-table quotes all row values via ',val, so an alist constant
;; cannot be a column — the body would receive the quoted symbol, not the list).

;; かん-cluster dict: "Ka" → min 3 chars; "Kan" → min 4 chars (e.g., かんしゃ).
(nskk-deftest-table dcomp-prefix-extends-reading-kan
  :columns (romaji-prefix min-expected-length)
  :rows (;; "Ka" → ▽かん → Tab → extended to 3+ chars (e.g., かんじ).
         ("Ka"  3)
         ;; "Kan" → ▽かん → Tab → extended to 4+ chars (e.g., かんしゃ).
         ("Kan" 4))
  :body
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
    (nskk-e2e-type romaji-prefix)
    (nskk-e2e-type "TAB")
    (nskk-e2e-assert-henkan-phase 'on)
    (should (>= (length (nskk-preedit-string)) min-expected-length))))

;; Extended dict: さくら ("Sa" → 3 chars) and にほん ("Ni" → 3 chars).
(nskk-deftest-table dcomp-prefix-extends-reading-extended
  :columns (romaji-prefix min-expected-length)
  :rows (;; "Sa" → ▽さ → Tab → さくら (3 chars).
         ("Sa"  3)
         ;; "Ni" → ▽に → Tab → にほん (3 chars).
         ("Ni"  3))
  :body
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict-extended
    (nskk-e2e-type romaji-prefix)
    (nskk-e2e-type "TAB")
    (nskk-e2e-assert-henkan-phase 'on)
    (should (>= (length (nskk-preedit-string)) min-expected-length))))

;;;;
;;;; Table-Driven Tests: non-matching prefixes remain unchanged
;;;;

;; For each romaji prefix that has no dict match, the preedit reading after TAB
;; must equal the preedit reading before TAB.  Dict is nskk-e2e--dcomp-dict
;; (かん-cluster only); "Mu", "To", "Xyz" have no matching prefix.
(nskk-deftest-table dcomp-no-match-prefix-unchanged
  :columns (romaji-prefix)
  :rows (;; "Xyz" → ▽xz? → no kana prefix → preedit unchanged.
         ("Xyz")
         ;; "Mu"  → "む" not in dict → preedit unchanged.
         ("Mu")
         ;; "To"  → "と" not in dict → preedit unchanged.
         ("To"))
  :body
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
    (nskk-e2e-type romaji-prefix)
    (let ((before (nskk-preedit-string)))
      (nskk-e2e-type "TAB")
      (should (equal before (nskk-preedit-string)))
      (nskk-e2e-assert-henkan-phase 'on))))

;;;;
;;;; nskk-deftest-cases: known prefix → completion is a string
;;;;

;; For each known romaji prefix, Tab must produce a preedit that is a string.
;; The exact completed value is not asserted here — only that completion ran
;; without error and produced a string result.
(nskk-deftest-cases dcomp-known-prefix-cases
  (("Ka" . t)   ; "Ka" → かん prefix → at least one completion in dict
   ("Sa" . t)   ; "Sa" → さ prefix → さくら in extended dict
   ("Ni" . t))  ; "Ni" → に prefix → にほん in extended dict
  :body
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict-extended
    (nskk-e2e-type input)
    (let ((before (nskk-preedit-string)))
      (nskk-e2e-type "TAB")
      ;; After Tab with a known prefix, preedit must be a valid string.
      (should (stringp (nskk-preedit-string)))
      ;; Suppress unused-variable warning: expected is always t (crash-free).
      (should expected))))

;;;;
;;;; dcomp SPC conversion after Tab completion
;;;;

(nskk-describe "dcomp SPC conversion after Tab completion"
  (nskk-it "SPC triggers conversion after Tab extends reading"
    ;; "Ka" → Tab → reading extended (e.g., ▽かんじ) → SPC → ▼ (active).
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      (nskk-e2e-type "TAB")
      ;; Confirm we are still in preedit phase with an extended reading.
      (nskk-e2e-assert-henkan-phase 'on)
      (should (> (length (nskk-preedit-string)) 0))
      ;; SPC should trigger henkan conversion.
      (nskk-e2e-type "SPC")
      ;; Now we should be in active conversion phase (▼).
      (nskk-e2e-assert-henkan-phase 'active)))

  (nskk-it "C-j after Tab commits the completed reading as kana"
    ;; "Ka" → Tab → reading extended → C-j → committed to buffer as kana.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      (nskk-e2e-type "TAB")
      (nskk-e2e-assert-henkan-phase 'on)
      ;; C-j commits the current preedit as kana without henkan.
      (nskk-e2e-type "C-j")
      ;; After commit, henkan phase returns to nil.
      (nskk-e2e-assert-henkan-phase nil)
      ;; Buffer should contain the committed kana (non-empty).
      (should (> (length (buffer-string)) 0)))))

;;;;
;;;; dcomp C-g after Tab cancels preedit
;;;;

(nskk-describe "dcomp C-g after Tab cancels preedit"
  (nskk-it "C-g cancels the entire preedit after Tab completion"
    ;; "Ka" → Tab → reading extended → C-g → preedit cancelled, buffer empty.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      (nskk-e2e-type "TAB")
      ;; Preedit is extended at this point.
      (nskk-e2e-assert-henkan-phase 'on)
      (should (> (length (nskk-preedit-string)) 0))
      ;; C-g cancels preedit.
      (nskk-e2e-type "C-g")
      ;; After cancellation, henkan phase is nil.
      (nskk-e2e-assert-henkan-phase nil)
      ;; Buffer should be empty (nothing was committed).
      (nskk-e2e-assert-buffer "")))

  (nskk-it "C-g without Tab also cancels partial preedit"
    ;; "Ka" → C-g → preedit cancelled without ever pressing Tab.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      (nskk-e2e-assert-henkan-phase 'on)
      (nskk-e2e-type "C-g")
      (nskk-e2e-assert-henkan-phase nil)
      (nskk-e2e-assert-buffer ""))))

;;;;
;;;; dcomp state invariants
;;;;

(nskk-describe "dcomp state invariants"
  (nskk-it "Tab in preedit never switches away from hiragana mode"
    ;; After typing a prefix and pressing Tab, the mode must remain hiragana.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      (nskk-e2e-type "TAB")
      (nskk-e2e-assert-mode 'hiragana)))

  (nskk-it "multiple Tabs in preedit do not switch mode"
    ;; Three Tab presses cycling through completions must not alter mode.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Kan")
      (nskk-e2e-type "TAB")
      (nskk-e2e-type "TAB")
      (nskk-e2e-type "TAB")
      (nskk-e2e-assert-mode 'hiragana)))

  (nskk-it "Tab on no-match prefix does not switch mode"
    ;; Tab with no completions must leave the mode unchanged.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
      (nskk-e2e-type "Xyz")
      (nskk-e2e-type "TAB")
      (nskk-e2e-assert-mode 'hiragana)))

  (nskk-it "preedit string is always a string after Tab"
    ;; The return value of nskk-preedit-string must always be a string,
    ;; never nil, after any combination of romaji input + Tab.
    (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict-extended
      (nskk-e2e-type "Kan")
      (nskk-e2e-type "TAB")
      (should (stringp (nskk-preedit-string)))
      (nskk-e2e-type "TAB")
      (should (stringp (nskk-preedit-string))))))

;;;;
;;;; Property-Based Tests
;;;;

;; PBT 1: Any romaji prefix followed by TAB must not crash.
;; This is the crash-freedom property: the dcomp code path must be robust
;; against arbitrary (but syntactically valid) romaji input.
(nskk-property-test-seeded dcomp-any-prefix-tab-no-crash
  ((romaji romaji-basic))
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
    (condition-case err
        (progn
          (nskk-e2e-type romaji)
          (nskk-e2e-type "TAB")
          t)
      (error
       (ert-fail (format "dcomp TAB after %S crashed: %s"
                         romaji (error-message-string err))))))
  30)

;; PBT 2: After any romaji input + TAB, nskk-preedit-string returns a string.
;; This guards against nil returns from the completion path.
(nskk-property-test-seeded dcomp-preedit-always-string
  ((romaji romaji-basic))
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
    (nskk-e2e-type romaji)
    (nskk-e2e-type "TAB")
    (stringp (nskk-preedit-string)))
  30)

;; PBT 3: Mode is always hiragana after any romaji input + TAB.
;; TAB must never trigger a mode switch as a side effect.
(nskk-property-test-seeded dcomp-mode-preserved-after-tab
  ((romaji romaji-basic))
  (nskk-e2e-with-buffer 'hiragana nskk-e2e--dcomp-dict
    (nskk-e2e-type romaji)
    (nskk-e2e-type "TAB")
    (eq (nskk-current-mode) 'hiragana))
  30)

(provide 'nskk-e2e-dcomp)
;;; nskk-e2e-dcomp.el ends here
